import QRCode from 'qrcode';
const AR=()=>document.documentElement.dir==='rtl';
const labelOf=(el:Element)=>Array.from(el.childNodes).filter(n=>n.nodeType===Node.TEXT_NODE).map(n=>n.textContent||'').join('').trim();
const handled=new Set(['قائمة سفر','Travel checklist','تقسيم الميزانية','Budget split','شهري/سنوي','Monthly/Annual','رصيد الإجازات','Leave balance','نهاية الخدمة','End of service','النسبة','مؤقت مذاكرة','Study timer','جدول الضرب','Times table','احتياج الماء التقريبي','Water estimate','BMR','مؤقت مطبخ','Kitchen timer','QR لرابط','QR for link','QR لنص','QR for text','QR لهاتف','QR for phone','QR لبريد','QR for email','QR لـ Wi-Fi','QR for Wi-Fi','رقم عشوائي','Random number','اختيار اسم','Pick a name','قرعة','Draw','رمي نرد','Dice','قلب عملة','Coin flip','عجلة اختيار','Choice wheel','عداد نقرات','Click counter','عداد أيام','Day counter','مولد قائمة','List maker','تقسيم قائمة','Split list','مؤقت تركيز','Focus timer','ملاحظات مؤقتة','Temporary notes']);
const fmt=(n:number)=>n.toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});
function css(){if(document.getElementById('dtAuditCss'))return;const s=document.createElement('style');s.id='dtAuditCss';s.textContent=`#dtAudit{position:fixed;inset:0;z-index:2147483647;background:rgba(7,29,73,.42);backdrop-filter:blur(8px);display:grid;place-items:center;padding:14px}#dtAudit .b{box-sizing:border-box;width:min(94vw,540px);max-height:90vh;overflow:auto;background:#fff;border-radius:28px;padding:24px;color:#0b315b;box-shadow:0 28px 80px rgba(7,29,73,.24)}#dtAudit h2{margin:5px 0 18px;font-size:27px}#dtAudit label{display:grid;gap:7px;margin:12px 0;font-weight:800}#dtAudit input,#dtAudit textarea,#dtAudit select{box-sizing:border-box;width:100%;min-height:54px;border:1px solid #cbddeb;border-radius:14px;padding:12px 14px;background:#f8fbfe;color:#0b315b;font:inherit;font-size:17px}#dtAudit textarea{min-height:130px;resize:vertical}#dtAudit .r{display:none;white-space:pre-wrap;overflow-wrap:anywhere;margin-top:14px;padding:16px;border-radius:15px;background:#eef7ff;font-weight:850;line-height:1.7}#dtAudit .err{min-height:21px;color:#b42318;font-weight:750}#dtAudit .a{display:flex;gap:9px;margin-top:16px;flex-wrap:wrap}#dtAudit button{flex:1;min-width:100px;border:0;border-radius:14px;padding:13px;font:inherit;font-weight:850}#dtAudit .go{background:#147dcc;color:#fff}#dtAudit .x,#dtAudit .alt{background:#eef6fc;color:#285779}#dtAudit canvas{display:block;max-width:260px;width:100%;height:auto;margin:12px auto;background:#fff;padding:10px;border-radius:14px}@media(max-width:650px){#dtAudit{align-items:end;padding:0}#dtAudit .b{width:100%;border-radius:28px 28px 0 0;padding:24px 18px 30px}}`;document.head.appendChild(s)}
type F={k:string,l:string,t?:string,p?:string};
function modal(title:string,fields:F[],goText?:string){css();document.getElementById('dtAudit')?.remove();const d=document.createElement('div');d.id='dtAudit';d.dir=AR()?'rtl':'ltr';d.innerHTML=`<div class="b"><small>${AR()?'أدواتك اليومية':'Daily Tools'}</small><h2></h2><div class="f"></div><div class="err"></div><div class="r"></div><div class="a"><button class="x">${AR()?'إغلاق':'Close'}</button><button class="go">${goText|| (AR()?'تنفيذ':'Run')}</button></div></div>`;(d.querySelector('h2') as HTMLElement).textContent=title;const w=d.querySelector('.f')!;fields.forEach(f=>{const l=document.createElement('label');l.textContent=f.l;const i=f.t==='textarea'?document.createElement('textarea'):document.createElement('input');i.className=f.k;if(i instanceof HTMLInputElement){i.type=f.t||'text';if(i.type==='number')i.inputMode='decimal'}i.setAttribute('placeholder',f.p||'');l.appendChild(i);w.appendChild(l)});document.body.appendChild(d);const close=()=>d.remove();(d.querySelector('.x') as HTMLButtonElement).onclick=close;d.onclick=e=>{if(e.target===d)close()};return {d,val:(k:string)=>(d.querySelector('.'+k) as HTMLInputElement|HTMLTextAreaElement)?.value.trim()||'',show:(x:string)=>{const r=d.querySelector('.r') as HTMLElement;r.textContent=x;r.style.display='block';(d.querySelector('.err') as HTMLElement).textContent=''},bad:(x?:string)=>{(d.querySelector('.err') as HTMLElement).textContent=x||(AR()?'أكمل البيانات بشكل صحيح':'Complete the fields correctly')},go:d.querySelector('.go') as HTMLButtonElement};}
const num=(s:string)=>Number(s.replace(/[٠-٩]/g,c=>String('٠١٢٣٤٥٦٧٨٩'.indexOf(c))).replace(/,/g,''));
function timer(title:string,minutesDefault='25'){const m=modal(title,[{k:'mins',l:AR()?'المدة بالدقائق':'Minutes',t:'number',p:minutesDefault}],AR()?'ابدأ':'Start');let id=0;m.go.onclick=()=>{const n=num(m.val('mins'));if(!Number.isFinite(n)||n<=0){m.bad();return}if(id)clearInterval(id);let left=Math.round(n*60);const paint=()=>{const mm=String(Math.floor(left/60)).padStart(2,'0'),ss=String(left%60).padStart(2,'0');m.show(left<=0?(AR()?'انتهى الوقت':'Time is up'):`${mm}:${ss}`);if(left--<=0)clearInterval(id)};paint();id=window.setInterval(paint,1000)}}
async function run(l:string){const ar=AR();
 if(/^(مؤقت مذاكرة|Study timer|مؤقت مطبخ|Kitchen timer|مؤقت تركيز|Focus timer)$/.test(l)){timer(l,l.includes('مطبخ')||l==='Kitchen timer'?'10':'25');return}
 if(l==='رمي نرد'||l==='Dice'){await (window as any).dtAlert(`${ar?'النتيجة':'Result'}: ${crypto.getRandomValues(new Uint32Array(1))[0]%6+1}`);return}if(l==='قلب عملة'||l==='Coin flip'){await (window as any).dtAlert(crypto.getRandomValues(new Uint32Array(1))[0]%2?(ar?'صورة':'Heads'):(ar?'كتابة':'Tails'));return}
 if(l==='عداد نقرات'||l==='Click counter'){const m=modal(l,[],ar?'انقر +1':'Tap +1');let n=0;m.show('0');m.go.onclick=()=>m.show(String(++n));return}
 if(l==='جدول الضرب'||l==='Times table'){const m=modal(l,[{k:'n',l:ar?'الرقم':'Number',t:'number'}]);m.go.onclick=()=>{const n=num(m.val('n'));if(!Number.isFinite(n)){m.bad();return}m.show(Array.from({length:12},(_,i)=>`${fmt(n)} × ${i+1} = ${fmt(n*(i+1))}`).join('\n'))};return}
 if(l==='النسبة'){const m=modal(l,[{k:'a',l:'القيمة',t:'number'},{k:'b',l:'من أصل',t:'number'}]);m.go.onclick=()=>{const a=num(m.val('a')),b=num(m.val('b'));b?m.show(`${fmt(a/b*100)}%`):m.bad()};return}
 if(l==='احتياج الماء التقريبي'||l==='Water estimate'){const m=modal(l,[{k:'w',l:ar?'الوزن بالكيلوغرام':'Weight in kg',t:'number'}]);m.go.onclick=()=>{const w=num(m.val('w'));w>0?m.show(`${fmt(w*0.033)} ${ar?'لتر/يوم تقريباً':'L/day approx.'}`):m.bad()};return}
 if(l==='BMR'){const m=modal(l,[{k:'w',l:ar?'الوزن كغ':'Weight kg',t:'number'},{k:'h',l:ar?'الطول سم':'Height cm',t:'number'},{k:'age',l:ar?'العمر':'Age',t:'number'},{k:'sex',l:ar?'الجنس: اكتب ذكر أو أنثى':'Sex: male or female'}]);m.go.onclick=()=>{const w=num(m.val('w')),h=num(m.val('h')),a=num(m.val('age')),s=m.val('sex').toLowerCase(),male=s==='ذكر'||s==='male',female=s==='أنثى'||s==='انثى'||s==='female';if(!(w>0&&h>0&&a>0&&(male||female))){m.bad();return}m.show(`${fmt(10*w+6.25*h-5*a+(male?5:-161))} kcal/day`)};return}
 if(l==='تقسيم الميزانية'||l==='Budget split'){const m=modal(l,[{k:'n',l:ar?'الدخل الشهري':'Monthly income',t:'number'}]);m.go.onclick=()=>{const n=num(m.val('n'));n>0?m.show(ar?`احتياجات 50%: ${fmt(n*.5)}\nرغبات 30%: ${fmt(n*.3)}\nادخار 20%: ${fmt(n*.2)}`:`Needs 50%: ${fmt(n*.5)}\nWants 30%: ${fmt(n*.3)}\nSavings 20%: ${fmt(n*.2)}`):m.bad()};return}
 if(l==='شهري/سنوي'||l==='Monthly/Annual'){const m=modal(l,[{k:'n',l:ar?'القيمة الشهرية':'Monthly amount',t:'number'}]);m.go.onclick=()=>{const n=num(m.val('n'));Number.isFinite(n)?m.show(`${ar?'سنوي':'Annual'}: ${fmt(n*12)}`):m.bad()};return}
 if(l==='رصيد الإجازات'||l==='Leave balance'){const m=modal(l,[{k:'total',l:ar?'الرصيد السنوي بالأيام':'Annual allowance days',t:'number'},{k:'used',l:ar?'الأيام المستخدمة':'Used days',t:'number'}]);m.go.onclick=()=>{const a=num(m.val('total')),b=num(m.val('used'));a>=0&&b>=0&&b<=a?m.show(`${fmt(a-b)} ${ar?'يوم متبقٍ':'days remaining'}`):m.bad()};return}
 if(l==='نهاية الخدمة'||l==='End of service'){const m=modal(l,[{k:'salary',l:ar?'الراتب الشهري':'Monthly salary',t:'number'},{k:'years',l:ar?'سنوات الخدمة':'Years of service',t:'number'}]);m.go.onclick=()=>{const s=num(m.val('salary')),y=num(m.val('years'));s>0&&y>=0?m.show((ar?'تقدير عام غير قانوني: ':'General non-legal estimate: ')+fmt(s*y)):m.bad()};return}
 if(l==='قائمة سفر'||l==='Travel checklist'){const key='dt-travel-list',m=modal(l,[{k:'t',l:ar?'العناصر، كل عنصر في سطر':'Items, one per line',t:'textarea'}],ar?'حفظ':'Save');(m.d.querySelector('.t') as HTMLTextAreaElement).value=localStorage.getItem(key)||'';m.go.onclick=()=>{const t=m.val('t');if(!t){m.bad();return}localStorage.setItem(key,t);m.show(ar?'تم حفظ القائمة على هذا الجهاز':'List saved on this device')};return}
 if(l==='ملاحظات مؤقتة'||l==='Temporary notes'){const key='dt-notes',m=modal(l,[{k:'t',l:ar?'ملاحظاتك':'Your notes',t:'textarea'}],ar?'حفظ':'Save');(m.d.querySelector('.t') as HTMLTextAreaElement).value=localStorage.getItem(key)||'';m.go.onclick=()=>{localStorage.setItem(key,m.val('t'));m.show(ar?'تم الحفظ على هذا الجهاز':'Saved on this device')};return}
 if(l==='عداد أيام'||l==='Day counter'){const m=modal(l,[{k:'d1',l:ar?'التاريخ الأول':'First date',t:'date'},{k:'d2',l:ar?'التاريخ الثاني':'Second date',t:'date'}]);m.go.onclick=()=>{const a=new Date(m.val('d1')+'T12:00:00'),b=new Date(m.val('d2')+'T12:00:00');isFinite(a.getTime())&&isFinite(b.getTime())?m.show(`${Math.abs(Math.round((b.getTime()-a.getTime())/86400000))} ${ar?'يوم':'days'}`):m.bad()};return}
 if(/^(مولد قائمة|List maker|تقسيم قائمة|Split list|اختيار اسم|Pick a name|قرعة|Draw|عجلة اختيار|Choice wheel)$/.test(l)){const m=modal(l,[{k:'t',l:ar?'أدخل العناصر، كل عنصر في سطر':'Enter items, one per line',t:'textarea'}]);m.go.onclick=()=>{const a=m.val('t').split('\n').map(x=>x.trim()).filter(Boolean);if(!a.length){m.bad();return}if(/^(مولد قائمة|List maker)$/.test(l)){m.show(a.map((x,i)=>`${i+1}. ${x}`).join('\n'));return}if(/^(تقسيم قائمة|Split list)$/.test(l)){const mid=Math.ceil(a.length/2);m.show(`${ar?'المجموعة 1':'Group 1'}:\n${a.slice(0,mid).join('\n')}\n\n${ar?'المجموعة 2':'Group 2'}:\n${a.slice(mid).join('\n')}`);return}const r=crypto.getRandomValues(new Uint32Array(1))[0]%a.length;m.show(`${ar?'الاختيار':'Choice'}: ${a[r]}`)};return}
 if(l==='رقم عشوائي'||l==='Random number'){const m=modal(l,[{k:'min',l:ar?'من':'Minimum',t:'number'},{k:'max',l:ar?'إلى':'Maximum',t:'number'}]);m.go.onclick=()=>{const a=Math.ceil(num(m.val('min'))),b=Math.floor(num(m.val('max')));if(!Number.isFinite(a)||!Number.isFinite(b)||b<a){m.bad();return}const range=b-a+1;m.show(String(a+(crypto.getRandomValues(new Uint32Array(1))[0]%range)))};return}
 if(l.startsWith('QR')||l.startsWith('QR ')){let fields:F[]=[{k:'v',l:ar?'المحتوى':'Content'}];if(l.includes('Wi-Fi'))fields=[{k:'ssid',l:'Wi-Fi SSID'},{k:'pass',l:ar?'كلمة المرور':'Password'}];const m=modal(l,fields,ar?'إنشاء QR':'Generate QR');m.go.onclick=async()=>{let v=m.val('v');if(l.includes('Wi-Fi')){const ssid=m.val('ssid');if(!ssid){m.bad();return}v=`WIFI:T:WPA;S:${ssid.replace(/([\\;,:"])/g,'\\$1')};P:${m.val('pass').replace(/([\\;,:"])/g,'\\$1')};;`}else if(!v){m.bad();return}if(l.includes('لهاتف')||l==='QR for phone')v='tel:'+v;if(l.includes('لبريد')||l==='QR for email')v='mailto:'+v;const old=m.d.querySelector('canvas');old?.remove();const c=document.createElement('canvas');m.d.querySelector('.r')?.after(c);await QRCode.toCanvas(c,v,{width:260,margin:2});m.show(ar?'تم إنشاء الرمز محلياً على جهازك':'QR generated locally on your device')};return}
}
window.addEventListener('click',e=>{const b=(e.target as Element|null)?.closest('.subgrid button') as HTMLElement|null;if(!b)return;const l=labelOf(b);if(!handled.has(l))return;e.preventDefault();e.stopImmediatePropagation();void run(l)},true);
export {};
