const ar=()=>document.documentElement.dir==='rtl';
const labelOf=(el:Element)=>Array.from(el.childNodes).filter(n=>n.nodeType===Node.TEXT_NODE).map(n=>n.textContent||'').join('').trim();
const fmt=(n:number)=>n.toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});
type Def={a:string;e:string;unit:string;calc:(n:number)=>number};
const defs:Record<string,Def>={
'الطول':{a:'الطول بالمتر',e:'Length in meters',unit:'cm',calc:n=>n*100},Length:{a:'الطول بالمتر',e:'Length in meters',unit:'cm',calc:n=>n*100},
'الوزن':{a:'الوزن بالكيلوغرام',e:'Weight in kilograms',unit:'lb',calc:n=>n*2.2046226218},Weight:{a:'الوزن بالكيلوغرام',e:'Weight in kilograms',unit:'lb',calc:n=>n*2.2046226218},
'تحويل الوزن':{a:'الوزن بالكيلوغرام',e:'Weight in kilograms',unit:'lb',calc:n=>n*2.2046226218},'Weight conversion':{a:'الوزن بالكيلوغرام',e:'Weight in kilograms',unit:'lb',calc:n=>n*2.2046226218},
'المساحة':{a:'المساحة بالمتر المربع',e:'Area in square meters',unit:'ft²',calc:n=>n*10.7639104},Area:{a:'المساحة بالمتر المربع',e:'Area in square meters',unit:'ft²',calc:n=>n*10.7639104},
'الحجم':{a:'الحجم باللتر',e:'Volume in liters',unit:'ml',calc:n=>n*1000},Volume:{a:'الحجم باللتر',e:'Volume in liters',unit:'ml',calc:n=>n*1000},
'الحرارة':{a:'الدرجة المئوية °C',e:'Celsius °C',unit:'°F',calc:n=>n*9/5+32},Temperature:{a:'الدرجة المئوية °C',e:'Celsius °C',unit:'°F',calc:n=>n*9/5+32},
'السرعة':{a:'السرعة كم/ساعة',e:'Speed km/h',unit:'mph',calc:n=>n/1.609344},Speed:{a:'السرعة كم/ساعة',e:'Speed km/h',unit:'mph',calc:n=>n/1.609344},
'ميل/كم':{a:'المسافة بالميل',e:'Distance in miles',unit:'km',calc:n=>n*1.609344},'Miles/Km':{a:'المسافة بالميل',e:'Distance in miles',unit:'km',calc:n=>n*1.609344},
'تحويل الطول':{a:'الطول بالسنتيمتر',e:'Height in centimeters',unit:'ft',calc:n=>n/30.48},'Height conversion':{a:'الطول بالسنتيمتر',e:'Height in centimeters',unit:'ft',calc:n=>n/30.48},
'جرام/كيلو':{a:'الوزن بالجرام',e:'Weight in grams',unit:'kg',calc:n=>n/1000},'Gram/Kg':{a:'الوزن بالجرام',e:'Weight in grams',unit:'kg',calc:n=>n/1000},
'مل/لتر':{a:'الحجم بالملليلتر',e:'Volume in milliliters',unit:'L',calc:n=>n/1000},'ml/L':{a:'الحجم بالملليلتر',e:'Volume in milliliters',unit:'L',calc:n=>n/1000},
'كوب/مل':{a:'عدد الأكواب',e:'Cups',unit:'ml',calc:n=>n*240},'Cup/ml':{a:'عدد الأكواب',e:'Cups',unit:'ml',calc:n=>n*240},
'مئوي/فهرنهايت':{a:'الدرجة المئوية °C',e:'Celsius °C',unit:'°F',calc:n=>n*9/5+32},'Celsius/Fahrenheit':{a:'الدرجة المئوية °C',e:'Celsius °C',unit:'°F',calc:n=>n*9/5+32}
};
function css(){if(document.getElementById('dtConvCss'))return;const s=document.createElement('style');s.id='dtConvCss';s.textContent=`#dtConv{position:fixed;inset:0;z-index:2147483647;background:rgba(7,29,73,.42);backdrop-filter:blur(8px);display:grid;place-items:center;padding:16px}#dtConv .b{width:min(94vw,500px);background:#fff;border-radius:27px;padding:24px;color:#0b315b;box-shadow:0 28px 80px rgba(7,29,73,.22)}#dtConv h2{margin:5px 0 20px;font-size:25px}#dtConv label{display:grid;gap:8px;font-weight:800}#dtConv input{width:100%;min-height:55px;box-sizing:border-box;border:1px solid #cbddeb;border-radius:15px;padding:12px 14px;background:#f8fbfe;color:#0b315b;font:inherit;font-size:18px}#dtConv .r{margin-top:16px;padding:15px;border-radius:15px;background:#eef7ff;font-size:22px;font-weight:900;display:none}#dtConv .err{min-height:22px;margin-top:8px;color:#b42318;font-weight:700}#dtConv .a{display:flex;gap:9px;margin-top:14px}#dtConv button{flex:1;border:0;border-radius:14px;padding:13px;font:inherit;font-weight:850}#dtConv .go{background:#147dcc;color:#fff}#dtConv .x{background:#eef6fc;color:#285779}@media(max-width:650px){#dtConv{align-items:end;padding:0}#dtConv .b{width:100%;border-radius:28px 28px 0 0;padding:25px 18px 30px}}`;document.head.appendChild(s)}
function open(title:string,d:Def){css();document.getElementById('dtConv')?.remove();const root=document.createElement('div');root.id='dtConv';root.dir=ar()?'rtl':'ltr';root.innerHTML=`<div class="b"><small>${ar()?'أدواتك اليومية':'Daily Tools'}</small><h2></h2><label><span></span><input type="number" inputmode="decimal" step="any" autocomplete="off"></label><div class="err"></div><div class="r"></div><div class="a"><button class="x">${ar()?'إغلاق':'Close'}</button><button class="go">${ar()?'تحويل':'Convert'}</button></div></div>`;(root.querySelector('h2') as HTMLElement).textContent=title;(root.querySelector('label span') as HTMLElement).textContent=ar()?d.a:d.e;document.body.appendChild(root);const input=root.querySelector('input') as HTMLInputElement,err=root.querySelector('.err') as HTMLElement,res=root.querySelector('.r') as HTMLElement;const close=()=>root.remove();(root.querySelector('.x') as HTMLButtonElement).onclick=close;root.onclick=e=>{if(e.target===root)close()};(root.querySelector('.go') as HTMLButtonElement).onclick=()=>{const raw=input.value.trim(),n=Number(raw);if(raw===''||!Number.isFinite(n)){err.textContent=ar()?'أدخل قيمة صحيحة أولاً':'Enter a valid value first';res.style.display='none';return}err.textContent='';res.textContent=`${fmt(d.calc(n))} ${d.unit}`;res.style.display='block'};setTimeout(()=>input.focus(),30)}
window.addEventListener('click',e=>{const btn=(e.target as Element|null)?.closest('.subgrid button') as HTMLElement|null;if(!btn)return;const label=labelOf(btn),d=defs[label];if(!d)return;e.preventDefault();e.stopImmediatePropagation();open(label,d)},true);
export {};
