const AR=()=>document.documentElement.dir==='rtl';
const labelOf=(el:Element)=>Array.from(el.childNodes).filter(n=>n.nodeType===Node.TEXT_NODE).map(n=>n.textContent||'').join('').trim();
const labels=new Set(['إضافة أيام','طرح أيام','Add days','Subtract days']);
const pad=(n:number)=>String(n).padStart(2,'0');
const format=(d:Date)=>`${pad(d.getDate())}/${pad(d.getMonth()+1)}/${d.getFullYear()}`;
function css(){if(document.getElementById('dtDateCss'))return;const s=document.createElement('style');s.id='dtDateCss';s.textContent=`#dtDateTool{position:fixed;inset:0;z-index:2147483647;background:rgba(7,29,73,.42);backdrop-filter:blur(8px);display:grid;place-items:center;padding:16px}#dtDateTool .box{width:min(94vw,510px);background:#fff;border-radius:28px;padding:24px;color:#0b315b;box-shadow:0 28px 80px rgba(7,29,73,.24)}#dtDateTool h2{margin:6px 0 20px;font-size:27px}#dtDateTool label{display:grid;gap:8px;margin:14px 0;font-weight:800}#dtDateTool input{width:100%;min-height:56px;box-sizing:border-box;border:1px solid #cbddeb;border-radius:15px;padding:12px 14px;background:#f8fbfe;color:#0b315b;font:inherit;font-size:18px}#dtDateTool .result{display:none;margin-top:16px;padding:18px;border-radius:16px;background:#eef7ff;font-size:25px;font-weight:900;text-align:center}#dtDateTool .err{min-height:22px;color:#b42318;font-weight:750}#dtDateTool .actions{display:flex;gap:9px;margin-top:16px}#dtDateTool button{flex:1;border:0;border-radius:14px;padding:14px;font:inherit;font-weight:850}#dtDateTool .go{background:#147dcc;color:#fff}#dtDateTool .close{background:#eef6fc;color:#285779}@media(max-width:650px){#dtDateTool{align-items:end;padding:0}#dtDateTool .box{width:100%;border-radius:28px 28px 0 0;padding:25px 18px 30px}}`;document.head.appendChild(s)}
function open(label:string){css();document.getElementById('dtDateTool')?.remove();const subtract=label==='طرح أيام'||label==='Subtract days';const d=document.createElement('div');d.id='dtDateTool';d.dir=AR()?'rtl':'ltr';d.innerHTML=`<div class="box"><small>${AR()?'أدواتك اليومية':'Daily Tools'}</small><h2></h2><label>${AR()?'اختر التاريخ':'Choose date'}<input class="date" type="date"></label><label>${AR()?'عدد الأيام':'Number of days'}<input class="days" type="number" inputmode="numeric" min="0" step="1"></label><div class="err" aria-live="polite"></div><div class="result" aria-live="polite"></div><div class="actions"><button class="close">${AR()?'إغلاق':'Close'}</button><button class="go">${AR()?(subtract?'اطرح الأيام':'أضف الأيام'):(subtract?'Subtract':'Add days')}</button></div></div>`;(d.querySelector('h2') as HTMLElement).textContent=label;document.body.appendChild(d);const date=d.querySelector('.date') as HTMLInputElement,days=d.querySelector('.days') as HTMLInputElement,err=d.querySelector('.err') as HTMLElement,res=d.querySelector('.result') as HTMLElement;date.value=new Date().toLocaleDateString('en-CA');const close=()=>d.remove();(d.querySelector('.close') as HTMLButtonElement).onclick=close;d.onclick=e=>{if(e.target===d)close()};(d.querySelector('.go') as HTMLButtonElement).onclick=()=>{const n=Number(days.value);if(!date.value||days.value===''||!Number.isInteger(n)||n<0){err.textContent=AR()?'اختر تاريخًا صحيحًا وأدخل عدد أيام صحيحًا':'Choose a valid date and enter a whole number of days';res.style.display='none';return}const [y,m,day]=date.value.split('-').map(Number);const out=new Date(y,m-1,day,12,0,0);out.setDate(out.getDate()+(subtract?-n:n));if(Number.isNaN(out.getTime())){err.textContent=AR()?'تعذر حساب التاريخ. تحقق من البيانات.':'Could not calculate the date. Check the inputs.';res.style.display='none';return}err.textContent='';res.textContent=format(out);res.style.display='block'};}
window.addEventListener('click',e=>{const btn=(e.target as Element|null)?.closest('.subgrid button') as HTMLElement|null;if(!btn)return;const label=labelOf(btn);if(!labels.has(label))return;e.preventDefault();e.stopImmediatePropagation();open(label)},true);
export {};
