type Field={label:string;type?:'number'|'text'|'date';placeholder?:string};
const AR=()=>document.documentElement.dir==='rtl';
const text=(el:Element)=>Array.from(el.childNodes).filter(n=>n.nodeType===Node.TEXT_NODE).map(n=>n.textContent||'').join('').trim();
const specs:Record<string,Field[]>={
'سعر المتر':[{label:'السعر الإجمالي'},{label:'المساحة بالمتر المربع'}],'Price per meter':[{label:'Total price'},{label:'Area in square meters'}],
'مساحة العقار':[{label:'الطول بالمتر'},{label:'العرض بالمتر'}],'Property area':[{label:'Length in meters'},{label:'Width in meters'}],
'تقسيم الإيجار':[{label:'قيمة الإيجار'},{label:'عدد الأشخاص'}],'Split rent':[{label:'Rent total'},{label:'Number of people'}],
'دفعة أولى':[{label:'سعر العقار'},{label:'نسبة الدفعة الأولى %'}],'Down payment':[{label:'Property price'},{label:'Down payment %'}],
'تكلفة الوقود':[{label:'المسافة (كم)'},{label:'الاستهلاك (لتر/100كم)'},{label:'سعر اللتر'}],'Fuel cost':[{label:'Distance (km)'},{label:'Consumption (L/100km)'},{label:'Price per liter'}],
'تكلفة الرحلة':[{label:'المسافة (كم)'},{label:'الاستهلاك (لتر/100كم)'},{label:'سعر اللتر'}],'Trip cost':[{label:'Distance (km)'},{label:'Consumption (L/100km)'},{label:'Price per liter'}],
'فائدة بسيطة':[{label:'رأس المال'},{label:'الفائدة السنوية %'},{label:'السنوات'}],'Simple interest':[{label:'Principal'},{label:'Annual rate %'},{label:'Years'}],
'فائدة مركبة':[{label:'رأس المال'},{label:'الفائدة السنوية %'},{label:'السنوات'}],'Compound interest':[{label:'Principal'},{label:'Annual rate %'},{label:'Years'}],
'ROI':[{label:'التكلفة'},{label:'القيمة النهائية'}],
'BMI':[{label:'الوزن (كغ)'},{label:'الطول (سم)'}],
'BMR':[{label:'الوزن (كغ)'},{label:'الطول (سم)'},{label:'العمر'}],
'مضاعفة الوصفة':[{label:'الكمية الأصلية'},{label:'عدد الحصص الأصلية'},{label:'عدد الحصص الجديدة'}],'Scale recipe':[{label:'Original amount'},{label:'Original servings'},{label:'New servings'}]
};
function style(){if(document.getElementById('dtSmartStyle'))return;const s=document.createElement('style');s.id='dtSmartStyle';s.textContent=`#dtSmart{position:fixed;inset:0;z-index:2147483646;background:rgba(7,29,73,.42);backdrop-filter:blur(8px);display:grid;place-items:center;padding:14px}#dtSmart .box{width:min(94vw,520px);max-height:90vh;overflow:auto;background:#fff;border-radius:26px;padding:24px;box-sizing:border-box;color:#0b315b;box-shadow:0 28px 80px rgba(7,29,73,.24)}#dtSmart h2{margin:4px 0 20px;font-size:27px}#dtSmart label{display:grid;gap:7px;margin:13px 0;font-weight:800}#dtSmart input{min-height:54px;box-sizing:border-box;width:100%;border:1px solid #cbddeb;border-radius:14px;padding:12px 14px;background:#f8fbfe;color:#0b315b;font:inherit;font-size:18px}#dtSmart .actions{display:flex;gap:9px;margin-top:20px}#dtSmart button{flex:1;border:0;border-radius:14px;padding:13px;font:inherit;font-weight:850}#dtSmart .go{background:#147dcc;color:white}#dtSmart .cancel{background:#eef6fc;color:#285779}#dtSmart .err{color:#b42318;margin:8px 0}`;document.head.appendChild(s)}
async function open(label:string,fields:Field[]){style();document.getElementById('dtSmart')?.remove();const d=document.createElement('div');d.id='dtSmart';d.dir=AR()?'rtl':'ltr';d.innerHTML=`<div class="box"><small>${AR()?'أدواتك اليومية':'Daily Tools'}</small><h2></h2><div class="fields"></div><div class="err" aria-live="polite"></div><div class="actions"><button class="cancel">${AR()?'إلغاء':'Cancel'}</button><button class="go">${AR()?'احسب':'Calculate'}</button></div></div>`;(d.querySelector('h2') as HTMLElement).textContent=label;const wrap=d.querySelector('.fields')!;fields.forEach((f,i)=>{const l=document.createElement('label');l.textContent=f.label;const input=document.createElement('input');input.type=f.type||'number';input.inputMode=f.type==='text'?'text':'decimal';input.dataset.i=String(i);l.appendChild(input);wrap.appendChild(l)});document.body.appendChild(d);return new Promise<string[]|null>(resolve=>{const done=(v:string[]|null)=>{d.remove();resolve(v)};(d.querySelector('.cancel') as HTMLButtonElement).onclick=()=>done(null);(d.querySelector('.go') as HTMLButtonElement).onclick=()=>{const vals=Array.from(d.querySelectorAll('input')).map(x=>(x as HTMLInputElement).value.trim());if(vals.some(v=>v==='')){(d.querySelector('.err') as HTMLElement).textContent=AR()?'أكمل جميع الحقول المطلوبة':'Complete all required fields';return}done(vals)};d.onclick=e=>{if(e.target===d)done(null)}})}
window.addEventListener('click',async e=>{const target=e.target as Element|null,btn=target?.closest('.subgrid button') as HTMLElement|null;if(!btn)return;const label=text(btn),fields=specs[label];if(!fields)return;e.preventDefault();e.stopImmediatePropagation();const vals=await open(label,fields);if(!vals)return;let i=0;const oldPrompt=window.prompt,oldAlert=window.alert;try{window.prompt=(()=>vals[i++]??'') as typeof window.prompt;window.alert=((m:any)=>{void (window as any).dtAlert(m)}) as typeof window.alert;(window as any).__dailyToolsRun?.(label)}finally{window.prompt=oldPrompt;window.alert=oldAlert}},true);
export {};
