type Field={label:string;type?:'number'|'text'|'date'};
const AR=()=>document.documentElement.dir==='rtl';
const text=(el:Element)=>Array.from(el.childNodes).filter(n=>n.nodeType===Node.TEXT_NODE).map(n=>n.textContent||'').join('').trim();
const N=(ar:string,en:string):Field=>({label:AR()?ar:en});
function fieldsFor(label:string):Field[]|null{
 const m:Record<string,Field[]>={
'الإيجار الشهري/السنوي':[N('الإيجار الشهري','Monthly rent')],'Monthly/annual rent':[N('الإيجار الشهري','Monthly rent')],
'سعر المتر':[N('السعر الإجمالي','Total price'),N('المساحة بالمتر المربع','Area m²')],'Price per meter':[N('السعر الإجمالي','Total price'),N('المساحة بالمتر المربع','Area m²')],
'مساحة العقار':[N('الطول بالمتر','Length m'),N('العرض بالمتر','Width m')],'Property area':[N('الطول بالمتر','Length m'),N('العرض بالمتر','Width m')],
'تقسيم الإيجار':[N('قيمة الإيجار','Rent total'),N('عدد الأشخاص','People')],'Split rent':[N('قيمة الإيجار','Rent total'),N('عدد الأشخاص','People')],
'دفعة أولى':[N('سعر العقار','Property price'),N('نسبة الدفعة الأولى %','Down payment %')],'Down payment':[N('سعر العقار','Property price'),N('نسبة الدفعة الأولى %','Down payment %')],
'ميزانية سكن':[N('الدخل الشهري','Monthly income'),N('النسبة المخصصة للسكن %','Housing %')],'Housing budget':[N('الدخل الشهري','Monthly income'),N('النسبة المخصصة للسكن %','Housing %')],
'تكلفة الوقود':[N('المسافة (كم)','Distance km'),N('الاستهلاك (لتر/100كم)','Consumption L/100km'),N('سعر اللتر','Price/liter')],'Fuel cost':[N('المسافة (كم)','Distance km'),N('الاستهلاك (لتر/100كم)','Consumption L/100km'),N('سعر اللتر','Price/liter')],
'استهلاك الوقود':[N('المسافة (كم)','Distance km'),N('الاستهلاك (لتر/100كم)','Consumption L/100km'),N('سعر اللتر','Price/liter')],'Fuel consumption':[N('المسافة (كم)','Distance km'),N('الاستهلاك (لتر/100كم)','Consumption L/100km'),N('سعر اللتر','Price/liter')],
'تكلفة الرحلة':[N('المسافة (كم)','Distance km'),N('الاستهلاك (لتر/100كم)','Consumption L/100km'),N('سعر اللتر','Price/liter')],'Trip cost':[N('المسافة (كم)','Distance km'),N('الاستهلاك (لتر/100كم)','Consumption L/100km'),N('سعر اللتر','Price/liter')],
'كم/لتر':[N('المسافة (كم)','Distance km'),N('اللترات','Liters')],'Km/L':[N('المسافة (كم)','Distance km'),N('اللترات','Liters')],
'لتر/100كم':[N('المسافة (كم)','Distance km'),N('اللترات','Liters')],'L/100km':[N('المسافة (كم)','Distance km'),N('اللترات','Liters')],
'فائدة بسيطة':[N('رأس المال','Principal'),N('الفائدة السنوية %','Annual rate %'),N('السنوات','Years')],'Simple interest':[N('رأس المال','Principal'),N('الفائدة السنوية %','Annual rate %'),N('السنوات','Years')],
'فائدة مركبة':[N('رأس المال','Principal'),N('الفائدة السنوية %','Annual rate %'),N('السنوات','Years')],'Compound interest':[N('رأس المال','Principal'),N('الفائدة السنوية %','Annual rate %'),N('السنوات','Years')],
'ROI':[N('التكلفة','Cost'),N('القيمة النهائية','Final value')],
'هدف الادخار':[N('الهدف','Goal'),N('عدد الأشهر','Months')],'Savings goal':[N('الهدف','Goal'),N('عدد الأشهر','Months')],
'الراتب الشهري/السنوي':[N('الراتب الشهري','Monthly salary')],'Monthly/annual salary':[N('الراتب الشهري','Monthly salary')],
'زيادة الراتب':[N('الراتب الحالي','Current salary'),N('نسبة الزيادة %','Increase %')],'Salary increase':[N('الراتب الحالي','Current salary'),N('نسبة الزيادة %','Increase %')],
'العمل الإضافي':[N('أجر الساعة','Hourly rate'),N('عدد الساعات','Hours')],'Overtime':[N('أجر الساعة','Hourly rate'),N('عدد الساعات','Hours')],
'بدل الإجازة':[N('الراتب الشهري','Monthly salary'),N('أيام الإجازة','Leave days')],'Leave pay':[N('الراتب الشهري','Monthly salary'),N('أيام الإجازة','Leave days')],
'BMI':[N('الوزن (كغ)','Weight kg'),N('الطول (سم)','Height cm')],
'BMR':[N('الوزن (كغ)','Weight kg'),N('الطول (سم)','Height cm'),N('العمر','Age')],
'Pace':[N('المسافة (كم)','Distance km'),N('الوقت بالدقائق','Minutes')],
'مضاعفة الوصفة':[N('الكمية الأصلية','Original amount'),N('الحصص الأصلية','Original servings'),N('الحصص الجديدة','New servings')],'Scale recipe':[N('الكمية الأصلية','Original amount'),N('الحصص الأصلية','Original servings'),N('الحصص الجديدة','New servings')],
'المعدل':[N('الأرقام مفصولة بفواصل','Numbers comma-separated')],'Average':[N('الأرقام مفصولة بفواصل','Numbers comma-separated')],
'المتوسط':[N('الأرقام مفصولة بفواصل','Numbers comma-separated')],'Mean':[N('الأرقام مفصولة بفواصل','Numbers comma-separated')],
'الدرجة المطلوبة':[N('المجموع الحالي','Current total'),N('المطلوب','Target')],'Required grade':[N('المجموع الحالي','Current total'),N('المطلوب','Target')]
 };return m[label]||null}
function style(){if(document.getElementById('dtSmartStyle'))return;const s=document.createElement('style');s.id='dtSmartStyle';s.textContent=`#dtSmart{position:fixed;inset:0;z-index:2147483647;background:rgba(7,29,73,.42);backdrop-filter:blur(8px);display:grid;place-items:center;padding:14px}#dtSmart .box{width:min(94vw,520px);max-height:90vh;overflow:auto;background:#fff;border-radius:26px;padding:24px;box-sizing:border-box;color:#0b315b;box-shadow:0 28px 80px rgba(7,29,73,.24)}#dtSmart h2{margin:6px 0 20px;font-size:27px}#dtSmart label{display:grid;gap:7px;margin:13px 0;font-weight:800}#dtSmart input{min-height:54px;box-sizing:border-box;width:100%;border:1px solid #cbddeb;border-radius:14px;padding:12px 14px;background:#f8fbfe;color:#0b315b;font:inherit;font-size:18px}#dtSmart .actions{display:flex;gap:9px;margin-top:20px}#dtSmart button{flex:1;border:0;border-radius:14px;padding:13px;font:inherit;font-weight:850}#dtSmart .go{background:#147dcc;color:white}#dtSmart .cancel{background:#eef6fc;color:#285779}#dtSmart .err{color:#b42318;margin:8px 0;font-weight:750}`;document.head.appendChild(s)}
async function open(label:string,fields:Field[]){style();document.getElementById('dtSmart')?.remove();const d=document.createElement('div');d.id='dtSmart';d.dir=AR()?'rtl':'ltr';d.innerHTML=`<div class="box"><small>${AR()?'أدواتك اليومية':'Daily Tools'}</small><h2></h2><div class="fields"></div><div class="err" aria-live="polite"></div><div class="actions"><button class="cancel">${AR()?'إلغاء':'Cancel'}</button><button class="go">${AR()?'احسب':'Calculate'}</button></div></div>`;(d.querySelector('h2') as HTMLElement).textContent=label;const wrap=d.querySelector('.fields')!;fields.forEach(f=>{const l=document.createElement('label');l.textContent=f.label;const input=document.createElement('input');input.type=f.type||'number';input.inputMode=f.type==='text'?'text':'decimal';l.appendChild(input);wrap.appendChild(l)});document.body.appendChild(d);return new Promise<string[]|null>(resolve=>{const done=(v:string[]|null)=>{d.remove();resolve(v)};(d.querySelector('.cancel') as HTMLButtonElement).onclick=()=>done(null);(d.querySelector('.go') as HTMLButtonElement).onclick=()=>{const vals=Array.from(d.querySelectorAll('input')).map(x=>(x as HTMLInputElement).value.trim());if(vals.some(v=>v==='')){(d.querySelector('.err') as HTMLElement).textContent=AR()?'أكمل جميع الحقول المطلوبة':'Complete all required fields';return}done(vals)};d.onclick=e=>{if(e.target===d)done(null)}})}
window.addEventListener('click',async e=>{const target=e.target as Element|null,btn=target?.closest('.subgrid button') as HTMLElement|null;if(!btn)return;const label=text(btn),fields=fieldsFor(label);if(!fields)return;e.preventDefault();e.stopImmediatePropagation();const vals=await open(label,fields);if(!vals)return;let i=0;const oldPrompt=window.prompt,oldAlert=window.alert;try{window.prompt=(()=>vals[i++]??'') as typeof window.prompt;window.alert=((m:any)=>{void (window as any).dtAlert(m)}) as typeof window.alert;(window as any).__dailyToolsRun?.(label)}finally{window.prompt=oldPrompt;window.alert=oldAlert}},true);
export {};
