import { useEffect, useMemo, useState } from 'react';
import { Calculator, CalendarDays, Clock3, Ruler, Car, Coins, House, BriefcaseBusiness, FileText, GraduationCap, HeartPulse, ChefHat, QrCode, ShieldCheck, Dices, Gamepad2, Wrench, Image, Video, Link as LinkIcon, Search, X, Info, Lightbulb, Globe2, CircleHelp, Star, Share2, History, Sparkles, MousePointerClick, Zap, LockKeyhole, BadgeCheck } from 'lucide-react';
type Lang='ar'|'en';
type Category={ar:string;en:string;descAr:string;descEn:string;toolsAr:string[];toolsEn:string[];icon:any};
type Page='home'|'about'|'help'|'vision'|'faq';
type ToolEntry={id:string;catIndex:number;toolIndex:number;ar:string;en:string;categoryAr:string;categoryEn:string};
type AssistantMatch={id:string;keywords:string[];replyAr:string;replyEn:string};
const LANG_KEY='dailyToolsLanguage',FAV_KEY='dailyToolsFavorites',RECENT_KEY='dailyToolsRecent';
const initialLang=():Lang=>{try{const saved=localStorage.getItem(LANG_KEY);if(saved==='ar'||saved==='en')return saved}catch{}return document.documentElement.lang==='en'?'en':'ar'};
const readIds=(key:string)=>{try{const v=JSON.parse(localStorage.getItem(key)||'[]');return Array.isArray(v)?v.filter(x=>typeof x==='string'):[]}catch{return[]}};
const data:Category[]=[
['الحاسبات','Calculators','العمر، النسبة، الخصم، الوقود','Age, percentage, discount and fuel',['حاسبة العمر','النسبة المئوية','الخصم','فرق تاريخين','تقسيم الفاتورة','تكلفة الوقود'],['Age calculator','Percentage','Discount','Date difference','Split bill','Fuel cost'],Calculator],
['التاريخ والتقويم','Date & Calendar','التواريخ وعدّ الأيام','Dates and day counting',['تاريخ اليوم','فرق تاريخين','إضافة أيام','طرح أيام','رقم الأسبوع','عد تنازلي'],['Today','Date difference','Add days','Subtract days','Week number','Countdown'],CalendarDays],
['الوقت والساعة','Time & Clock','الوقت والمؤقتات','Time and timers',['ساعة رقمية','مؤقت','ساعة إيقاف','تحويل ساعات ودقائق','مدة زمنية'],['Digital clock','Timer','Stopwatch','Hours & minutes','Duration'],Clock3],
['تحويل الوحدات','Unit Conversion','الطول والوزن والمساحة','Length, weight and area',['الطول','الوزن','المساحة','الحجم','الحرارة','السرعة'],['Length','Weight','Area','Volume','Temperature','Speed'],Ruler],
['السيارة والسفر','Car & Travel','حسابات مفيدة للمسافر','Useful travel calculations',['استهلاك الوقود','تكلفة الرحلة','كم/لتر','لتر/100كم','ميل/كم','قائمة سفر'],['Fuel consumption','Trip cost','Km/L','L/100km','Miles/Km','Travel checklist'],Car],
['المال والادخار','Money & Savings','خطط وحسابات مالية بسيطة','Simple financial planning',['هدف الادخار','فائدة بسيطة','فائدة مركبة','ROI','تقسيم الميزانية','شهري/سنوي'],['Savings goal','Simple interest','Compound interest','ROI','Budget split','Monthly/Annual'],Coins],
['العقار والسكن','Property & Housing','حسابات عقارية','Property calculations',['الإيجار الشهري/السنوي','سعر المتر','مساحة العقار','تقسيم الإيجار','دفعة أولى','ميزانية سكن'],['Monthly/annual rent','Price per meter','Property area','Split rent','Down payment','Housing budget'],House],
['الموظف والراتب','Employee & Salary','حسابات الموظفين والإجازات','Salary and leave calculations',['الراتب الشهري/السنوي','زيادة الراتب','العمل الإضافي','رصيد الإجازات','بدل الإجازة','نهاية الخدمة'],['Monthly/annual salary','Salary increase','Overtime','Leave balance','Leave pay','End of service'],BriefcaseBusiness],
['أدوات النصوص','Text Tools','معالجة النص داخل جهازك','Local text utilities',['عد الكلمات','عد الحروف','إزالة الفراغات','ترتيب الأسطر','إزالة التكرار','وقت القراءة'],['Word count','Character count','Trim spaces','Sort lines','Remove duplicates','Reading time'],FileText],
['التعليم','Education','حسابات وأدوات دراسية','Study utilities',['المعدل','النسبة','المتوسط','الدرجة المطلوبة','مؤقت مذاكرة','جدول الضرب'],['Average','Percentage','Mean','Required grade','Study timer','Times table'],GraduationCap],
['الصحة العامة','General Health','مؤشرات عامة غير تشخيصية','General non-diagnostic estimates',['BMI','تحويل الطول','تحويل الوزن','احتياج الماء التقريبي','BMR','Pace'],['BMI','Height conversion','Weight conversion','Water estimate','BMR','Pace'],HeartPulse],
['المطبخ','Kitchen','مقاييس ووحدات الطبخ','Cooking measurements',['جرام/كيلو','مل/لتر','كوب/مل','مئوي/فهرنهايت','مضاعفة الوصفة','مؤقت مطبخ'],['Gram/Kg','ml/L','Cup/ml','Celsius/Fahrenheit','Scale recipe','Kitchen timer'],ChefHat],
['الرموز والباركود','QR & Barcode','أدوات QR محلية','Local QR utilities',['QR لرابط','QR لنص','QR لهاتف','QR لبريد','QR لـ Wi-Fi'],['QR for link','QR for text','QR for phone','QR for email','QR for Wi-Fi'],QrCode],
['الأمان والخصوصية','Security & Privacy','أدوات حماية بسيطة','Simple privacy tools',['مولد كلمة مرور','فحص القوة محلياً','مولد PIN','عبارة مرور','نصائح حماية'],['Password generator','Password strength','PIN generator','Passphrase','Protection tips'],ShieldCheck],
['الاختيار والقرعة','Random & Draw','اختيارات عشوائية','Random choices',['رقم عشوائي','اختيار اسم','قرعة','رمي نرد','قلب عملة','عجلة اختيار'],['Random number','Pick a name','Draw','Dice','Coin flip','Choice wheel'],Dices],
['الألعاب','Games','ألعاب خفيفة','Light games',['XO','حجر ورقة مقص','تحدي حساب','ألغاز'],['Tic Tac Toe','Rock Paper Scissors','Math challenge','Puzzles'],Gamepad2],
['أدوات يومية متنوعة','Daily Utilities','أدوات صغيرة مفيدة','Small useful utilities',['عداد نقرات','عداد أيام','مولد قائمة','تقسيم قائمة','مؤقت تركيز','ملاحظات مؤقتة'],['Click counter','Day counter','List maker','Split list','Focus timer','Temporary notes'],Wrench],
['مواقع الصور','Image Websites','روابط لخدمات خارجية موثوقة','Links to independent services',['ضغط الصور','تغيير الحجم','إزالة الخلفية','تحويل الصيغ','تصميم الصور'],['Compress images','Resize images','Remove background','Convert formats','Image design'],Image],
['مواقع الفيديو','Video Websites','روابط لخدمات خارجية موثوقة','Links to independent services',['قص الفيديو','ضغط الفيديو','تحويل الصيغة','تحرير الفيديو','تسجيل الشاشة'],['Trim video','Compress video','Convert format','Video editing','Screen recording'],Video],
['مواقع مفيدة','Useful Websites','دليل روابط منتقاة','Curated useful links',['تعليم','إنتاجية','سفر','تقنية','مراجع'],['Education','Productivity','Travel','Technology','References'],LinkIcon]
].map(x=>({ar:x[0],en:x[1],descAr:x[2],descEn:x[3],toolsAr:x[4],toolsEn:x[5],icon:x[6]})) as Category[];
const tools:ToolEntry[]=data.flatMap((c,catIndex)=>c.toolsAr.map((ar,toolIndex)=>({id:`c${catIndex}-t${toolIndex}`,catIndex,toolIndex,ar,en:c.toolsEn[toolIndex],categoryAr:c.ar,categoryEn:c.en})));
const assistantMatches:AssistantMatch[]=[
 {id:'c0-t0',keywords:['كم عمري','عمري','العمر','age','birthday','ميلادي'],replyAr:'سأفتح حاسبة العمر لك.',replyEn:'Opening the age calculator.'},{id:'c0-t2',keywords:['خصم','تخفيض','discount','sale'],replyAr:'سأفتح حاسبة الخصم.',replyEn:'Opening the discount calculator.'},{id:'c0-t4',keywords:['قسم الفاتورة','تقسيم الفاتورة','فاتورة','bill','split'],replyAr:'سأفتح أداة تقسيم الفاتورة.',replyEn:'Opening bill splitting.'},{id:'c4-t1',keywords:['تكلفة الرحلة','تكلفة مشوار','تكلفة سفر','trip cost','مشوار'],replyAr:'سأفتح حاسبة تكلفة الرحلة.',replyEn:'Opening trip cost.'},{id:'c4-t0',keywords:['استهلاك الوقود','استهلاك سيارة','بنزين','fuel consumption'],replyAr:'سأفتح حاسبة استهلاك الوقود.',replyEn:'Opening fuel consumption.'},{id:'c1-t5',keywords:['رمضان','عد تنازلي','countdown','كم باقي'],replyAr:'سأفتح العدّ التنازلي.',replyEn:'Opening countdown.'},{id:'c3-t5',keywords:['ميل الى كم','ميل إلى كم','miles to km','سرعة','كم/س','kmh'],replyAr:'سأفتح تحويل السرعة والمسافة.',replyEn:'Opening speed conversion.'},{id:'c3-t4',keywords:['فهرنهايت','مئوي','حرارة','celsius','fahrenheit'],replyAr:'سأفتح تحويل الحرارة.',replyEn:'Opening temperature conversion.'},{id:'c5-t0',keywords:['ادخار','وفر','هدف مالي','savings'],replyAr:'سأفتح حاسبة هدف الادخار.',replyEn:'Opening savings goal.'},{id:'c8-t0',keywords:['عد الكلمات','كلمات','word count','كم كلمة'],replyAr:'سأفتح عداد الكلمات.',replyEn:'Opening word count.'},{id:'c12-t4',keywords:['واي فاي','wifi','شبكة','كود واي فاي'],replyAr:'سأفتح QR لشبكة Wi‑Fi.',replyEn:'Opening Wi‑Fi QR.'},{id:'c12-t0',keywords:['qr','باركود','رابط كود','رمز qr'],replyAr:'سأفتح مولد QR للرابط.',replyEn:'Opening QR generator.'},{id:'c13-t0',keywords:['كلمة مرور','باسورد','password'],replyAr:'سأفتح مولد كلمة المرور.',replyEn:'Opening password generator.'},{id:'c10-t0',keywords:['bmi','كتلة الجسم','وزني','وزن وطول'],replyAr:'سأفتح حاسبة BMI.',replyEn:'Opening BMI calculator.'}
];
const faq=[
['هل استخدام أدواتك اليومية مجاني؟','Are Daily Tools free to use?','نعم. الأدوات الأساسية متاحة مجاناً، ويمكن استخدامها مباشرة دون إنشاء حساب.','Yes. Core tools are available for free and can be used without creating an account.'],
['هل أحتاج إلى تسجيل حساب؟','Do I need an account?','لا. صُممت الأدوات اليومية لتصل إلى الأداة التي تحتاجها بسرعة ومن دون تسجيل.','No. Daily Tools is designed so you can reach useful tools quickly without signing up.'],
['هل تعمل الأدوات على الهاتف والكمبيوتر؟','Do the tools work on mobile and desktop?','نعم. الواجهة مصممة للعمل على الهواتف والأجهزة اللوحية وأجهزة الكمبيوتر الحديثة.','Yes. The interface is designed for modern phones, tablets and desktop computers.'],
['هل الموقع متوفر بالعربية والإنجليزية؟','Is the site available in Arabic and English?','نعم. يمكنك التبديل بين العربية والإنجليزية من زر اللغة أعلى الموقع.','Yes. You can switch between Arabic and English using the language button at the top.'],
['هل تحفظون البيانات التي أدخلها في الأدوات؟','Do you store the data I enter into tools?','الأدوات المحلية مصممة لمعالجة مدخلاتها داخل تجربتك على الجهاز قدر الإمكان. لا تدخل معلومات حساسة في أي خدمة خارجية.','Local tools are designed to process inputs within your device experience whenever possible. Do not enter sensitive information into external services.'],
['لماذا تفتح بعض الأدوات موقعاً خارجياً؟','Why do some tools open an external website?','بعض خدمات الصور والفيديو والمراجع تقدمها مواقع مستقلة. الروابط الخارجية للتسهيل فقط وتخضع لشروط وسياسات أصحابها.','Some image, video and reference services are provided by independent websites. External links are provided for convenience and follow their owners’ terms and policies.'],
['هل النتائج المالية أو الصحية رسمية؟','Are financial or health results official?','لا. النتائج الحسابية والتقديرية للإرشاد العام فقط، ولا تستبدل المختص أو الجهة الرسمية.','No. Calculations and estimates are for general guidance only and do not replace a professional or an official source.'],
['ماذا أفعل إذا لم تعمل أداة كما يجب؟','What should I do if a tool does not work correctly?','لا تعتمد على نتيجة تبدو غير منطقية. أعد التحقق من المدخلات، ويمكن الإبلاغ عن المشكلة ليتم تحسين الأداة.','Do not rely on a result that looks incorrect. Check your inputs again and report the issue so the tool can be improved.']
];
export default function App(){
 const [lang,setLang]=useState<Lang>(initialLang),[q,setQ]=useState(''),[open,setOpen]=useState<number|null>(null),[page,setPage]=useState<Page>('home');
 const [assistantQuery,setAssistantQuery]=useState(''),[assistantReply,setAssistantReply]=useState('');
 const [favs,setFavs]=useState<string[]>(()=>readIds(FAV_KEY)); const [recent,setRecent]=useState<string[]>(()=>readIds(RECENT_KEY)); const ar=lang==='ar';
 document.documentElement.lang=lang;document.documentElement.dir=ar?'rtl':'ltr';
 const query=q.trim().toLowerCase();
 const shown=useMemo(()=>data.map((c,i)=>({c,i})).filter(({c})=>!query||(c.ar+' '+c.en+' '+c.descAr+' '+c.descEn+' '+c.toolsAr.join(' ')+' '+c.toolsEn.join(' ')).toLowerCase().includes(query)),[query]);
 const toolMatches=useMemo(()=>query?tools.filter(t=>(t.ar+' '+t.en+' '+t.categoryAr+' '+t.categoryEn).toLowerCase().includes(query)).slice(0,12):[],[query]);
 const byIds=(ids:string[])=>ids.map(id=>tools.find(t=>t.id===id)).filter(Boolean) as ToolEntry[];
 const favTools=byIds(favs),recentTools=byIds(recent);
 const toggle=()=>{const n:Lang=ar?'en':'ar';setLang(n);try{localStorage.setItem(LANG_KEY,n)}catch{}setOpen(null)};
 const go=(p:Page)=>{setPage(p);setOpen(null);window.scrollTo({top:0,behavior:'smooth'})};
 // Tool actions use one explicit application event.  Do not synthesize DOM clicks:
 // several legacy tool modules used document/window click capture, which could
 // intercept one another and leave the UI appearing unresponsive on mobile.
 const runTool=(t:ToolEntry)=>window.dispatchEvent(new CustomEvent('dailytools:launch',{detail:{label:ar?t.ar:t.en},cancelable:true}));
 const launch=(t:ToolEntry)=>{setOpen(t.catIndex);setTimeout(()=>runTool(t),80)};
 const askAssistant=(value=assistantQuery)=>{const normalized=value.trim().toLowerCase();if(!normalized){setAssistantReply(ar?'اكتب مهمة من أدواتك اليومية وسأوصلك للأداة المناسبة.':'Tell me a Daily Tools task and I’ll find the right tool.');return}const hit=assistantMatches.map(m=>({m,score:m.keywords.reduce((total,k)=>total+(normalized.includes(k)?k.length:0),0)})).sort((a,b)=>b.score-a.score)[0];if(!hit?.score){setAssistantReply(ar?'عذرًا، أنا مساعد أدواتك اليومية فقط. أستطيع مساعدتك بالحسابات والتحويل والنصوص وQR والمهام اليومية داخل هذا الموقع.':'Sorry, I only help with Daily Tools tasks inside this website.');return}const t=tools.find(x=>x.id===hit.m.id);if(!t)return;setAssistantReply(ar?hit.m.replyAr:hit.m.replyEn);launch(t)};
 const toggleFav=(id:string)=>{setFavs(prev=>{const next=prev.includes(id)?prev.filter(x=>x!==id):[id,...prev];try{localStorage.setItem(FAV_KEY,JSON.stringify(next))}catch{}return next})};
 const share=async(t:ToolEntry)=>{const url=`${location.origin}${location.pathname}#tool=${t.id}`;const title=ar?t.ar:t.en;try{if(navigator.share)await navigator.share({title,text:`${title} — ${ar?'أدواتك اليومية':'Daily Tools'}`,url});else{await navigator.clipboard.writeText(url);alert(ar?'تم نسخ رابط الأداة':'Tool link copied')}}catch{}};
 useEffect(()=>{const handler=(e:Event)=>{const text=(e as CustomEvent<string>).detail;const t=tools.find(x=>x.ar===text||x.en===text);if(!t)return;setRecent(prev=>{const next=[t.id,...prev.filter(x=>x!==t.id)].slice(0,8);try{localStorage.setItem(RECENT_KEY,JSON.stringify(next))}catch{}return next})};window.addEventListener('dailytools:used',handler);return()=>window.removeEventListener('dailytools:used',handler)},[]);
 useEffect(()=>{const m=location.hash.match(/^#tool=(c\d+-t\d+)$/);if(!m)return;const t=tools.find(x=>x.id===m[1]);if(t){setPage('home');setTimeout(()=>launch(t),120)}},[]);
 useEffect(()=>{if(open===null){document.title=ar?'أدواتك اليومية | Daily Tools — أدوات مجانية للحساب والتحويل والنصوص':'Daily Tools — Free calculators, converters and utilities';return}const c=data[open];document.title=`${ar?c.ar:c.en} | ${ar?'أدواتك اليومية':'Daily Tools'}`},[open,ar]);
 const ToolChip=({t}: {t:ToolEntry})=><div className="quickTool"><button className="quickMain" onClick={()=>launch(t)}><b>{ar?t.ar:t.en}</b><small>{ar?t.categoryAr:t.categoryEn}</small></button><button className={`miniAction ${favs.includes(t.id)?'active':''}`} onClick={()=>toggleFav(t.id)} aria-label={ar?'إضافة للمفضلة':'Add to favorites'}><Star size={17} fill={favs.includes(t.id)?'currentColor':'none'}/></button><button className="miniAction" onClick={()=>share(t)} aria-label={ar?'مشاركة':'Share'}><Share2 size={17}/></button></div>;
 return <main dir={ar?'rtl':'ltr'}><header><button className="brand" onClick={()=>go('home')}><i>MO</i><span>{ar?'أدواتك اليومية':'Daily Tools'}<small>{ar?'كل ما تحتاجه في مكان واحد':'Everything you need in one place'}</small></span></button><nav><button onClick={()=>go('home')}>{ar?'الرئيسية':'Home'}</button><button onClick={()=>{go('home');setTimeout(()=>document.getElementById('tools')?.scrollIntoView({behavior:'smooth'}),50)}}>{ar?'كل الأدوات':'All tools'}</button><button onClick={()=>go('about')}>{ar?'عن الموقع':'About'}</button><button className="lang" onClick={toggle} aria-label={ar?'Switch to English':'التبديل إلى العربية'}><Globe2 size={20}/><span>{ar?'EN':'العربية'}</span></button></nav></header>
 {page==='home'&&<><section className="hero"><div><span className="pill">{ar?'مجاني • سريع • بدون تسجيل':'Free • Fast • No sign-up'}</span><h1>{ar?'أدواتك اليومية':'Your Daily Tools'}</h1><p>{ar?'أدوات بسيطة .. نتائج كبيرة .. لحياة أسهل':'Simple tools • Big results • An easier life'}</p><label className="search"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder={ar?'ابحث باسم الأداة مباشرة...':'Search any tool by name...'}/>{q&&<button onClick={()=>setQ('')} aria-label={ar?'مسح البحث':'Clear search'}><X/></button>}</label>{toolMatches.length>0&&<div className="searchSuggestions">{toolMatches.map(t=><ToolChip key={t.id} t={t}/>)}</div>}</div><div className="heroArt" aria-label={ar?'مجموعة من الأدوات اليومية':'A collection of daily tools'}><div className="artPromise"><strong>{ar?'كل ما تحتاجه':'Everything you need'}</strong><span>{ar?'في مكان واحد':'in one place'}</span><i/></div></div></section><section className="dailyAssistant" aria-label={ar?'مساعدك اليومي':'Your daily assistant'}><div className="assistantIntro"><span><Sparkles size={19}/>{ar?'مساعدك اليومي':'Your daily assistant'}</span><h2>{ar?'قل لي ماذا تريد، وسأوصلك للأداة':'Tell me what you need — I’ll open the tool'}</h2><p>{ar?'يفهم طلبك بالعربي ويعمل داخل جهازك فقط.':'Understands your request and works entirely in your browser.'}</p></div><form className="assistantForm" onSubmit={e=>{e.preventDefault();askAssistant()}}><label><Search size={20}/><input value={assistantQuery} onChange={e=>setAssistantQuery(e.target.value)} placeholder={ar?'مثال: كم تكلفة مشوار من الرياض إلى جدة؟':'Example: How much will my trip cost?'}/></label><button type="submit">{ar?'اعثر على الأداة':'Find my tool'}</button></form><div className="assistantSamples">{(ar?['كم عمري؟','احسب تكلفة مشوار','حوّل ميل إلى كم','أنشئ QR للواي فاي']:['How old am I?','Calculate my trip cost','Convert miles to km','Create a Wi-Fi QR']).map(sample=><button key={sample} onClick={()=>{setAssistantQuery(sample);askAssistant(sample)}}>{sample}</button>)}</div>{assistantReply&&<p className="assistantReply" role="status"><Zap size={17}/>{assistantReply}</p>}</section>
 {(favTools.length>0||recentTools.length>0)&&<section className="personalTools">{favTools.length>0&&<div><div className="compactTitle"><Star/><b>{ar?'المفضلة':'Favorites'}</b></div><div className="quickGrid">{favTools.slice(0,8).map(t=><ToolChip key={t.id} t={t}/>)}</div></div>}{recentTools.length>0&&<div><div className="compactTitle"><History/><b>{ar?'استخدمتها مؤخرًا':'Recently used'}</b></div><div className="quickGrid">{recentTools.slice(0,8).map(t=><ToolChip key={t.id} t={t}/>)}</div></div>}</section>}
 <section id="tools" className="tools"><div className="sectionTitle"><div><span>{ar?'صندوق أدواتك':'Your toolbox'}</span><h2>{ar?'جميع الأدوات':'All tools'}</h2></div><span className="toolCount"><Sparkles size={16}/>{ar?`${tools.length} أداة وخدمة`:`${tools.length} tools & services`}</span></div>{shown.length?<div className="grid">{shown.map(({c,i})=>{const Icon=c.icon;return <button className="card" key={c.ar} onClick={()=>setOpen(i)}><span className="icon"><Icon/></span><b>{ar?c.ar:c.en}</b><small>{ar?c.descAr:c.descEn}</small><em>{ar?`${c.toolsAr.length} خيارات`:`${c.toolsEn.length} options`}</em></button>})}</div>:<div className="empty">{ar?'لم نجد أداة بهذا الاسم.':'No matching tool found.'}</div>}</section>
 <section className="dailyBanner"><div><b>{ar?'معك في كل يوم':'With you every day'}</b><span>{ar?'أدوات عملية • سريعة • في مكان واحد':'Practical • fast • all in one place'}</span></div><button onClick={()=>document.getElementById('tools')?.scrollIntoView({behavior:'smooth'})}>{ar?'اكتشف كل الأدوات':'Explore all tools'}</button></section><section className="benefits">{[
 [MousePointerClick,'سهولة الاستخدام','Easy to use','واجهة واضحة تصل منها إلى أداتك بسرعة.','A clear interface that gets you to the right tool quickly.'],
 [Zap,'سريع وخفيف','Fast & light','أدوات مباشرة وتجربة سريعة على الهاتف والكمبيوتر.','Direct tools and a fast experience on mobile and desktop.'],
 [LockKeyhole,'خصوصيتك أولاً','Privacy first','نعالج البيانات محلياً داخل جهازك قدر الإمكان.','We process data locally on your device whenever possible.'],
 [BadgeCheck,'مفيد دائماً','Always useful','أدوات عملية للحساب والتحويل والنصوص والمهام اليومية.','Practical tools for calculations, conversions, text and everyday tasks.']
].map(([I,a,e,da,de]:any)=><div key={a}><I/><b>{ar?a:e}</b><small>{ar?da:de}</small></div>)}</section><section className="infoMenu">{[[Info,'عن الموقع','About','about'],[Lightbulb,'كيف يفيدك؟','How it helps','help'],[Globe2,'رؤيتنا','Our vision','vision'],[CircleHelp,'الأسئلة الشائعة','FAQ','faq']].map(([I,a,e,p]:any)=><button key={p} onClick={()=>go(p as Page)}><I/><b>{ar?a:e}</b></button>)}</section></>}
 {page!=='home'&&<section className="page"><button onClick={()=>go('home')}>{ar?'العودة للرئيسية':'Back to home'}</button><h1>{page==='about'?(ar?'عن أدواتك اليومية':'About Daily Tools'):page==='help'?(ar?'كيف يفيدك الموقع؟':'How Daily Tools Helps'):page==='vision'?(ar?'رؤيتنا':'Our Vision'):(ar?'الأسئلة الشائعة':'Frequently Asked Questions')}</h1>{page==='faq'?<div className="faqList">{faq.map((f,i)=><details key={i} open={i===0}><summary>{ar?f[0]:f[1]}</summary><p>{ar?f[2]:f[3]}</p></details>)}</div>:<p>{page==='about'?(ar?'منصة عملية تجمع الأدوات اليومية في تجربة واضحة وسريعة تعمل من الهاتف والكمبيوتر، مع مفضلة وسجل حديث وروابط مشاركة مباشرة.':'A practical platform that brings everyday utilities into one fast experience with favorites, recent history and direct sharing.'):page==='help'?(ar?'ابحث باسم الأداة مباشرة، احفظ ما تستخدمه في المفضلة، وارجع تلقائياً إلى آخر الأدوات التي استخدمتها.':'Search any tool directly, save favorites and jump back to your recently used tools.'):ar?'أن تصبح أدواتك اليومية وجهتك الأولى للأدوات البسيطة التي تحتاجها كل يوم.':'To make Daily Tools your first stop for simple utilities you rely on every day.'}</p>}</section>}
 <footer style={{display:'flex',justifyContent:'center',alignItems:'center',gap:'28px',flexWrap:'wrap'}}><img src="https://raw.githubusercontent.com/Moqleh/daily-tools/main/MO%20LOGO.png?v=3" alt="MO" style={{width:'110px',height:'auto',display:'block'}} /><a href="mailto:info.moqleh@yahoo.com" style={{color:'inherit',textDecoration:'none',fontWeight:700}}>info.moqleh@yahoo.com</a></footer>
 {open!==null&&<div className="modalBack" onClick={()=>setOpen(null)}><section className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setOpen(null)}><X/></button>{(()=>{const c=data[open],Icon=c.icon,catTools=tools.filter(t=>t.catIndex===open);return <><span className="icon"><Icon/></span><h2>{ar?c.ar:c.en}</h2><p className="modalDesc">{ar?c.descAr:c.descEn}</p><div className="subgrid">{catTools.map(t=><div className="toolRow" key={t.id}><button className="toolLaunch" data-tool-id={t.id} onClick={()=>runTool(t)}>{ar?t.ar:t.en}<small>{ar?'فتح الأداة':'Open tool'}</small></button><div className="toolActions"><button className={favs.includes(t.id)?'active':''} onClick={()=>toggleFav(t.id)} aria-label={ar?'مفضلة':'Favorite'}><Star size={18} fill={favs.includes(t.id)?'currentColor':'none'}/></button><button onClick={()=>share(t)} aria-label={ar?'مشاركة':'Share'}><Share2 size={18}/></button></div></div>)}</div>{['الصحة العامة','الموظف والراتب','المال والادخار'].includes(c.ar)&&<div className="notice">{ar?'النتائج تقديرية وإرشادية وليست بديلاً عن الاستشارة المتخصصة أو المصدر الرسمي.':'Results are estimates for guidance only and do not replace professional advice or official sources.'}</div>}</>})()}</section></div>}
 </main>
}
