import { useMemo, useState } from 'react';
import { Calculator, CalendarDays, Clock3, Ruler, Car, PiggyBank, House, BriefcaseBusiness, FileText, GraduationCap, HeartPulse, ChefHat, QrCode, ShieldCheck, Dices, Gamepad2, Wrench, Image, Video, Link as LinkIcon, Search, X, Info, Lightbulb, Globe2, CircleHelp } from 'lucide-react';
type Lang='ar'|'en'; type Category={ar:string;en:string;descAr:string;descEn:string;toolsAr:string[];toolsEn:string[];icon:any};
const data:Category[]=[
['الحاسبات','Calculators','العمر، النسبة، الخصم، الوقود','Age, percentage, discount and fuel',['حاسبة العمر','النسبة المئوية','الخصم','فرق تاريخين','تقسيم الفاتورة','تكلفة الوقود'],['Age calculator','Percentage','Discount','Date difference','Split bill','Fuel cost'],Calculator],
['التاريخ والتقويم','Date & Calendar','التواريخ وعدّ الأيام','Dates and day counting',['تاريخ اليوم','فرق تاريخين','إضافة أيام','طرح أيام','رقم الأسبوع','عد تنازلي'],['Today','Date difference','Add days','Subtract days','Week number','Countdown'],CalendarDays],
['الوقت والساعة','Time & Clock','الوقت والمؤقتات','Time and timers',['ساعة رقمية','مؤقت','ساعة إيقاف','تحويل ساعات ودقائق','مدة زمنية'],['Digital clock','Timer','Stopwatch','Hours & minutes','Duration'],Clock3],
['تحويل الوحدات','Unit Conversion','الطول والوزن والمساحة','Length, weight and area',['الطول','الوزن','المساحة','الحجم','الحرارة','السرعة'],['Length','Weight','Area','Volume','Temperature','Speed'],Ruler],
['السيارة والسفر','Car & Travel','حسابات مفيدة للمسافر','Useful travel calculations',['استهلاك الوقود','تكلفة الرحلة','كم/لتر','لتر/100كم','ميل/كم','قائمة سفر'],['Fuel consumption','Trip cost','Km/L','L/100km','Miles/Km','Travel checklist'],Car],
['المال والادخار','Money & Savings','خطط وحسابات مالية بسيطة','Simple financial planning',['هدف الادخار','فائدة بسيطة','فائدة مركبة','ROI','تقسيم الميزانية','شهري/سنوي'],['Savings goal','Simple interest','Compound interest','ROI','Budget split','Monthly/Annual'],PiggyBank],
['العقار والسكن','Property & Housing','حسابات عقارية','Property calculations',['الإيجار الشهري/السنوي','سعر المتر','مساحة العقار','تقسيم الإيجار','دفعة أولى','ميزانية سكن'],['Monthly/annual rent','Price per meter','Property area','Split rent','Down payment','Housing budget'],House],
['الموظف والراتب','Employee & Salary','حسابات الموظفين والإجازات','Salary and leave calculations',['الراتب الشهري/السنوي','زيادة الراتب','العمل الإضافي','رصيد الإجازات','بدل الإجازة','نهاية الخدمة'],['Monthly/annual salary','Salary increase','Overtime','Leave balance','Leave pay','End of service'],BriefcaseBusiness],
['أدوات النصوص','Text Tools','معالجة النص داخل جهازك','Local text utilities',['عد الكلمات','عد الحروف','إزالة الفراغات','ترتيب الأسطر','إزالة التكرار','وقت القراءة'],['Word count','Character count','Trim spaces','Sort lines','Remove duplicates','Reading time'],FileText],
['التعليم','Education','حسابات وأدوات دراسية','Study utilities',['المعدل','النسبة','المتوسط','الدرجة المطلوبة','مؤقت مذاكرة','جدول الضرب'],['Average','Percentage','Mean','Required grade','Study timer','Times table'],GraduationCap],
['الصحة العامة','General Health','مؤشرات عامة غير تشخيصية','General non-diagnostic estimates',['BMI','تحويل الطول','تحويل الوزن','احتياج الماء التقريبي','BMR','Pace'],['BMI','Height conversion','Weight conversion','Water estimate','BMR','Pace'],HeartPulse],
['المطبخ','Kitchen','مقاييس ووحدات الطبخ','Cooking measurements',['جرام/كيلو','مل/لتر','كوب/مل','مئوي/فهرنهايت','مضاعفة الوصفة','مؤقت مطبخ'],['Gram/Kg','ml/L','Cup/ml','Celsius/Fahrenheit','Scale recipe','Kitchen timer'],ChefHat],
['الرموز والباركود','QR & Barcode','أدوات QR محلية','Local QR utilities',['QR لرابط','QR لنص','QR لهاتف','QR لبريد','QR لـ Wi-Fi'],['QR for link','QR for text','QR for phone','QR for email','QR for Wi-Fi'],QrCode],
['الأمان والخصوصية','Security & Privacy','أدوات حماية بسيطة','Simple privacy tools',['مولد كلمة مرور','فحص القوة محلياً','مولد PIN','عبارة مرور','نصائح حماية'],['Password generator','Password strength','PIN generator','Passphrase','Protection tips'],ShieldCheck],
['الاختيار والقرعة','Random & Draw','اختيارات عشوائية','Random choices',['رقم عشوائي','اختيار اسم','قرعة','رمي نرد','قلب عملة','عجلة اختيار'],['Random number','Pick a name','Draw','Dice','Coin flip','Choice wheel'],Dices],
['الألعاب','Games','ألعاب خفيفة','Light games',['XO','حجر ورقة مقص','تحدي حساب','ألغاز'],['Tic Tac Toe','Rock Paper Scissors','Math challenge','Puzzles'],Gamepad2],
['أدوات يومية متنوعة','Daily Utilities','أدوات صغيرة مفيدة','Small useful utilities',['عداد نقرات','عداد أيام','مولد قائمة','تقسيم قائمة','مؤقت تركيز','ملاحظات مؤقتة'],['Click counter','Day counter','List maker','Split list','Focus timer','Temporary notes'],Wrench],
['مواقع الصور','Image Websites','روابط لخدمات خارجية موثوقة','Links to independent services',['ضغط الصور','تغيير الحجم','إزالة الخلفية','تحويل الصيغ','تصميم الصور'],['Compress images','Resize images','Remove background','Convert formats','Image design'],Image],
['مواقع الفيديو','Video Websites','روابط لخدمات خارجية موثوقة','Links to independent services',['قص الفيديو','ضغط الفيديو','تحويل الصيغة','تحرير الفيديو','تسجيل الشاشة'],['Trim video','Compress video','Convert format','Video editing','Screen recording'],Video],
['مواقع مفيدة','Useful Websites','دليل روابط منتقاة','Curated useful links',['تعليم','إنتاجية','سفر','تقنية','مراجع'],['Education','Productivity','Travel','Technology','References'],LinkIcon]
].map(x=>({ar:x[0],en:x[1],descAr:x[2],descEn:x[3],toolsAr:x[4],toolsEn:x[5],icon:x[6]})) as Category[];
export default function App(){
 const [lang,setLang]=useState<Lang>('ar'),[q,setQ]=useState(''),[open,setOpen]=useState<number|null>(null),[page,setPage]=useState<'home'|'about'|'help'|'vision'|'faq'>('home'); const ar=lang==='ar';
 const shown=useMemo(()=>data.map((c,i)=>({c,i})).filter(({c})=>(c.ar+' '+c.en+' '+c.descAr+' '+c.descEn+' '+c.toolsAr.join(' ')+' '+c.toolsEn.join(' ')).toLowerCase().includes(q.trim().toLowerCase())),[q]);
 const toggle=()=>{const n:Lang=ar?'en':'ar';setLang(n);document.documentElement.lang=n;document.documentElement.dir=n==='ar'?'rtl':'ltr';setOpen(null)}; const go=(p:typeof page)=>{setPage(p);setOpen(null);window.scrollTo({top:0,behavior:'smooth'})};
 const run=(x:string)=>{const k=x.toLowerCase(),ask=(m:string)=>prompt(m),num=(m:string)=>Number(prompt(m)||0),out=(v:any)=>alert(String(v)),nums=()=>((ask(ar?'أدخل الأرقام مفصولة بفواصل':'Enter numbers separated by commas')||'').split(',').map(Number).filter(Number.isFinite));
 if(k.includes('age')||x.includes('العمر')){const y=num(ar?'سنة الميلاد':'Birth year');if(y)out((ar?'العمر التقريبي: ':'Approximate age: ')+(new Date().getFullYear()-y))}
 else if(k.includes('percentage')||x.includes('النسبة')){const a=num(ar?'الرقم':'Value'),b=num(ar?'النسبة %':'Percentage %');out((a*b/100).toFixed(2))}
 else if(k.includes('discount')||x==='الخصم'){const a=num(ar?'السعر':'Price'),b=num(ar?'الخصم %':'Discount %');out((a*(1-b/100)).toFixed(2))}
 else if(k.includes('split bill')||x==='تقسيم الفاتورة'){const a=num(ar?'قيمة الفاتورة':'Bill total'),b=num(ar?'عدد الأشخاص':'People');if(b)out((a/b).toFixed(2))}
 else if(k.includes('today')||x==='تاريخ اليوم')out(new Date().toLocaleDateString(ar?'ar-SA':'en-US',{dateStyle:'full'}));
 else if(k.includes('date difference')||x==='فرق تاريخين'){const a=new Date(ask(ar?'التاريخ الأول YYYY-MM-DD':'First date YYYY-MM-DD')||''),b=new Date(ask(ar?'التاريخ الثاني YYYY-MM-DD':'Second date YYYY-MM-DD')||'');out(Math.round(Math.abs(+b-+a)/86400000)+(ar?' يوم':' days'))}
 else if(k.includes('add days')||x==='إضافة أيام'||k.includes('subtract days')||x==='طرح أيام'){const d=new Date(ask(ar?'التاريخ YYYY-MM-DD':'Date YYYY-MM-DD')||''),n=num(ar?'عدد الأيام':'Days'),sub=k.includes('subtract')||x.includes('طرح');d.setDate(d.getDate()+(sub?-n:n));out(d.toLocaleDateString())}
 else if(k.includes('week number')||x==='رقم الأسبوع'){const d=new Date(),s=new Date(d.getFullYear(),0,1);out(Math.ceil((((+d-+s)/86400000)+s.getDay()+1)/7))}
 else if(k.includes('digital clock')||x==='ساعة رقمية')out(new Date().toLocaleTimeString(ar?'ar-SA':'en-US'));
 else if(k.includes('hours & minutes')||x==='تحويل ساعات ودقائق'){const h=num(ar?'الساعات':'Hours');out((h*60)+(ar?' دقيقة':' minutes'))}
 else if(k.includes('length')||x==='الطول'){const m=num(ar?'متر':'Meters');out((m*100).toFixed(2)+' cm | '+(m*3.28084).toFixed(2)+' ft')}
 else if(k.includes('weight')||x==='الوزن'||k.includes('weight conversion')||x==='تحويل الوزن'){const kg=num(ar?'كيلوغرام':'Kilograms');out((kg*2.20462).toFixed(2)+' lb')}
 else if(k.includes('area')||x==='المساحة'){const m=num(ar?'متر مربع':'Square meters');out((m*10.7639).toFixed(2)+' ft²')}
 else if(k.includes('volume')||x==='الحجم'){const l=num(ar?'لتر':'Liters');out((l*1000).toFixed(0)+' ml')}
 else if(k.includes('temperature')||k.includes('celsius')||x.includes('الحرارة')||x.includes('مئوي')){const c=num(ar?'الدرجة المئوية':'Celsius');out((c*9/5+32).toFixed(1)+' °F')}
 else if(k.includes('speed')||x==='السرعة'){const v=num(ar?'كم/ساعة':'km/h');out((v/1.609344).toFixed(2)+' mph')}
 else if(k.includes('miles')||x==='ميل/كم'){const m=num(ar?'المسافة بالميل':'Miles');out((m*1.609344).toFixed(2)+' km')}
 else if(k.includes('fuel')||x.includes('الوقود')||x.includes('الرحلة')){const km=num(ar?'المسافة كم':'Distance km'),eff=num(ar?'الاستهلاك لتر/100كم':'Consumption L/100km'),price=num(ar?'سعر اللتر':'Price per liter');out((km*eff/100*price).toFixed(2))}
 else if(k==='km/l'||x==='كم/لتر'){const km=num(ar?'المسافة كم':'Distance km'),l=num(ar?'اللترات':'Liters');if(l)out((km/l).toFixed(2)+' km/L')}
 else if(k.includes('l/100')||x==='لتر/100كم'){const km=num(ar?'المسافة كم':'Distance km'),l=num(ar?'اللترات':'Liters');if(km)out((l/km*100).toFixed(2)+' L/100km')}
 else if(k.includes('simple interest')||x==='فائدة بسيطة'){const p=num(ar?'رأس المال':'Principal'),r=num(ar?'الفائدة السنوية %':'Annual rate %'),y=num(ar?'السنوات':'Years');out((p*r/100*y).toFixed(2))}
 else if(k.includes('compound interest')||x==='فائدة مركبة'){const p=num(ar?'رأس المال':'Principal'),r=num(ar?'الفائدة السنوية %':'Annual rate %'),y=num(ar?'السنوات':'Years');out((p*Math.pow(1+r/100,y)).toFixed(2))}
 else if(k==='roi'||x==='ROI'){const cost=num(ar?'التكلفة':'Cost'),gain=num(ar?'القيمة النهائية':'Final value');if(cost)out((((gain-cost)/cost)*100).toFixed(2)+'%')}
 else if(k.includes('savings goal')||x==='هدف الادخار'){const goal=num(ar?'الهدف':'Goal'),months=num(ar?'عدد الأشهر':'Months');if(months)out((goal/months).toFixed(2)+(ar?' شهرياً':' monthly'))}
 else if(k.includes('monthly/annual')||x.includes('شهري/سنوي')||x.includes('الراتب الشهري')){const a=num(ar?'المبلغ الشهري':'Monthly amount');out((a*12).toFixed(2)+(ar?' سنوياً':' annually'))}
 else if(k.includes('salary increase')||x==='زيادة الراتب'){const s=num(ar?'الراتب الحالي':'Current salary'),p=num(ar?'نسبة الزيادة %':'Increase %');out((s*(1+p/100)).toFixed(2))}
 else if(k.includes('overtime')||x==='العمل الإضافي'){const rate=num(ar?'أجر الساعة':'Hourly rate'),h=num(ar?'الساعات الإضافية':'Overtime hours'),m=num(ar?'المعامل (مثلاً 1.5)':'Multiplier (e.g. 1.5)')||1.5;out((rate*h*m).toFixed(2))}
 else if(k.includes('price per meter')||x==='سعر المتر'){const price=num(ar?'السعر الإجمالي':'Total price'),area=num(ar?'المساحة م²':'Area m²');if(area)out((price/area).toFixed(2))}
 else if(k.includes('split rent')||x==='تقسيم الإيجار'){const rent=num(ar?'الإيجار':'Rent'),n=num(ar?'عدد الأشخاص':'People');if(n)out((rent/n).toFixed(2))}
 else if(k.includes('down payment')||x==='دفعة أولى'){const price=num(ar?'السعر':'Price'),p=num(ar?'نسبة الدفعة %':'Down payment %');out((price*p/100).toFixed(2))}
 else if(k.includes('word count')||x==='عد الكلمات'||k.includes('character count')||x==='عد الحروف'){const t=ask(ar?'أدخل النص':'Enter text')||'';out(k.includes('character')||x==='عد الحروف'?t.length:t.trim().split(/\s+/).filter(Boolean).length)}
 else if(k.includes('trim spaces')||x==='إزالة الفراغات'){const t=ask(ar?'أدخل النص':'Enter text')||'';out(t.replace(/\s+/g,' ').trim())}
 else if(k.includes('sort lines')||x==='ترتيب الأسطر'){const t=ask(ar?'أدخل الأسطر':'Enter lines')||'';out(t.split('\n').sort().join('\n'))}
 else if(k.includes('remove duplicates')||x==='إزالة التكرار'){const t=ask(ar?'أدخل الأسطر':'Enter lines')||'';out([...new Set(t.split('\n'))].join('\n'))}
 else if(k.includes('reading time')||x==='وقت القراءة'){const t=ask(ar?'أدخل النص':'Enter text')||'',w=t.trim().split(/\s+/).filter(Boolean).length;out(Math.max(1,Math.ceil(w/200))+(ar?' دقيقة تقريباً':' min approx.'))}
 else if(k.includes('average')||k==='mean'||x==='المعدل'||x==='المتوسط'){const a=nums();if(a.length)out((a.reduce((s,n)=>s+n,0)/a.length).toFixed(2))}
 else if(k.includes('required grade')||x==='الدرجة المطلوبة'){const cur=num(ar?'درجتك الحالية':'Current grade'),weight=num(ar?'وزن النهائي %':'Final weight %'),target=num(ar?'الدرجة المستهدفة':'Target grade');if(weight)out(((target-cur*(1-weight/100))/(weight/100)).toFixed(2))}
 else if(k.includes('times table')||x==='جدول الضرب'){const n=num(ar?'الرقم':'Number');out(Array.from({length:10},(_,i)=>`${n} × ${i+1} = ${n*(i+1)}`).join('\n'))}
 else if(k==='bmi'||x==='BMI'){const w=num(ar?'الوزن بالكيلو':'Weight kg'),h=num(ar?'الطول بالسنتيمتر':'Height cm');if(w&&h)out('BMI: '+(w/(h/100)**2).toFixed(1))}
 else if(k.includes('height conversion')||x==='تحويل الطول'){const cm=num(ar?'السنتيمترات':'Centimeters');out((cm/2.54).toFixed(2)+' in')}
 else if(k.includes('water estimate')||x.includes('احتياج الماء')){const w=num(ar?'الوزن بالكيلو':'Weight kg');out((w*0.033).toFixed(2)+(ar?' لتر/يوم تقريباً':' L/day approx.'))}
 else if(k==='bmr'||x==='BMR'){const w=num(ar?'الوزن كغ':'Weight kg'),h=num(ar?'الطول سم':'Height cm'),age=num(ar?'العمر':'Age'),sex=(ask(ar?'اكتب ذكر أو أنثى':'Type male or female')||'').toLowerCase();out(Math.round(10*w+6.25*h-5*age+(sex.includes('male')||sex.includes('ذكر')?5:-161)))}
 else if(k.includes('gram/kg')||x==='جرام/كيلو'){const g=num(ar?'الجرام':'Grams');out((g/1000).toFixed(3)+' kg')}
 else if(k.includes('ml/l')||x==='مل/لتر'){const ml=num(ar?'الملليلتر':'Milliliters');out((ml/1000).toFixed(3)+' L')}
 else if(k.includes('cup/ml')||x==='كوب/مل'){const cup=num(ar?'عدد الأكواب':'Cups');out((cup*240).toFixed(0)+' ml')}
 else if(k.includes('scale recipe')||x==='مضاعفة الوصفة'){const qty=num(ar?'الكمية الأصلية':'Original quantity'),from=num(ar?'عدد الحصص الأصلية':'Original servings'),to=num(ar?'عدد الحصص الجديدة':'New servings');if(from)out((qty*to/from).toFixed(2))}
 else if(k.includes('password generator')||x==='مولد كلمة مرور'){const c='ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#$%',a=new Uint32Array(16);crypto.getRandomValues(a);out(Array.from(a,n=>c[n%c.length]).join(''))}
 else if(k.includes('password strength')||x.includes('فحص القوة')){const p=ask(ar?'أدخل كلمة المرور (الفحص محلي)':'Enter password (checked locally)')||'',score=[p.length>=12,/[A-Z]/.test(p),/[a-z]/.test(p),/\d/.test(p),/[^\w]/.test(p)].filter(Boolean).length;out((ar?'القوة: ':'Strength: ')+(['ضعيفة جداً','ضعيفة','متوسطة','جيدة','قوية','قوية جداً'][score]))}
 else if(k.includes('pin generator')||x==='مولد PIN')out(String(Math.floor(100000+Math.random()*900000)));
 else if(k.includes('passphrase')||x==='عبارة مرور'){const w=['blue','river','cloud','stone','olive','moon','cedar','light'],a=new Uint32Array(4);crypto.getRandomValues(a);out(Array.from(a,n=>w[n%w.length]).join('-'))}
 else if(k.includes('protection tips')||x==='نصائح حماية')out(ar?'استخدم كلمة مرور فريدة، فعّل التحقق بخطوتين، ولا تشارك رموز الدخول.':'Use unique passwords, enable 2FA, and never share login codes.');
 else if(k.includes('random number')||x==='رقم عشوائي')out(Math.floor(Math.random()*100)+1); else if(k.includes('dice')||x==='رمي نرد')out(Math.floor(Math.random()*6)+1); else if(k.includes('coin')||x==='قلب عملة')out(Math.random()<.5?(ar?'وجه':'Heads'):(ar?'كتابة':'Tails'));
 else if(k.includes('pick')||k==='draw'||x==='اختيار اسم'||x==='قرعة'||x==='عجلة اختيار'){const a=(ask(ar?'أدخل الخيارات مفصولة بفواصل':'Options separated by commas')||'').split(',').map(s=>s.trim()).filter(Boolean);if(a.length)out(a[Math.floor(Math.random()*a.length)])}
 else if(k.includes('rock paper')||x==='حجر ورقة مقص'){const choices=ar?['حجر','ورقة','مقص']:['Rock','Paper','Scissors'];out(choices[Math.floor(Math.random()*3)])}
 else if(k.includes('math challenge')||x==='تحدي حساب'){const a=Math.ceil(Math.random()*20),b=Math.ceil(Math.random()*20),ans=num(`${a} + ${b} = ?`);out(ans===a+b?(ar?'صحيح!':'Correct!'):(ar?`الإجابة ${a+b}`:`Answer: ${a+b}`))}
 else if(k.includes('puzzles')||x==='ألغاز')out(ar?'لغز: شيء كلما أخذت منه كبر، ما هو؟ الحفرة.':'Riddle: What gets bigger the more you take away? A hole.');
 else if(k.includes('click counter')||x==='عداد نقرات'){const n=Number(localStorage.getItem('clickCount')||0)+1;localStorage.setItem('clickCount',String(n));out(n)}
 else if(k.includes('list maker')||x==='مولد قائمة'){const t=ask(ar?'اكتب العناصر مفصولة بفواصل':'Items separated by commas')||'';out(t.split(',').map((v,i)=>`${i+1}. ${v.trim()}`).join('\n'))}
 else if(k.includes('split list')||x==='تقسيم قائمة'){const a=(ask(ar?'العناصر مفصولة بفواصل':'Comma-separated items')||'').split(',');out((ar?'المجموعة 1: ':'Group 1: ')+a.filter((_,i)=>i%2===0).join(', ')+'\n'+(ar?'المجموعة 2: ':'Group 2: ')+a.filter((_,i)=>i%2).join(', '))}
 else if(k.includes('temporary notes')||x==='ملاحظات مؤقتة'){const t=prompt(ar?'اكتب ملاحظتك':'Write your note',localStorage.getItem('dailyNote')||'');if(t!==null){localStorage.setItem('dailyNote',t);out(ar?'تم الحفظ على هذا الجهاز':'Saved on this device')}}
 else if(k.includes('qr')||x.includes('QR'))out(ar?'سيتم إضافة مولّد QR محلي كامل في التحديث التالي.':'A full local QR generator will be added in the next update.');
 else if(['ضغط الصور','تغيير الحجم','إزالة الخلفية','تحويل الصيغ','تصميم الصور','قص الفيديو','ضغط الفيديو','تحويل الصيغة','تحرير الفيديو','تسجيل الشاشة','تعليم','إنتاجية','سفر','تقنية','مراجع'].includes(x)||['compress images','resize images','remove background','convert formats','image design','trim video','compress video','convert format','video editing','screen recording','education','productivity','travel','technology','references'].includes(k))out(ar?'هذا القسم دليل لخدمات خارجية مستقلة، وسيتم ربط الروابط المنتقاة فقط.':'This section is a directory of independent external services; curated links will be connected separately.');
 else out(ar?'هذه الأداة تحتاج واجهة تفاعلية خاصة، وسيتم تشغيلها في المرحلة التالية.':'This tool needs a dedicated interactive interface and will be activated in the next stage.'); };
 return <main dir={ar?'rtl':'ltr'}><header><button className="brand" onClick={()=>go('home')}><i>MO</i><span>{ar?'أدواتك اليومية':'Daily Tools'}<small>{ar?'كل ما تحتاجه في مكان واحد':'Everything you need in one place'}</small></span></button><nav><button onClick={()=>go('home')}>{ar?'الرئيسية':'Home'}</button><button onClick={()=>{go('home');setTimeout(()=>document.getElementById('tools')?.scrollIntoView({behavior:'smooth'}),50)}}>{ar?'كل الأدوات':'All tools'}</button><button onClick={()=>go('about')}>{ar?'عن الموقع':'About'}</button><button className="lang" onClick={toggle}>{ar?'EN':'العربية'}</button></nav></header>
 {page==='home'&&<><section className="hero"><div><span className="pill">{ar?'مجاني • سريع • بدون تسجيل':'Free • Fast • No sign-up'}</span><h1>{ar?'أدواتك اليومية':'Your Daily Tools'}</h1><p>{ar?'أدوات بسيطة .. نتائج كبيرة .. لحياة أسهل':'Simple tools. Big results. An easier day.'}</p><label className="search"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder={ar?'ابحث عن أداة...':'Search for a tool...'}/>{q&&<button onClick={()=>setQ('')}><X/></button>}</label></div><div className="heroArt"><div className="glass"><b>{ar?'أدوات عملية':'Practical tools'}</b><span>{ar?'في حياتك اليومية':'for everyday life'}</span></div></div></section><section id="tools" className="tools"><div className="sectionTitle"><div><span>{ar?'صندوق أدواتك':'Your toolbox'}</span><h2>{ar?'جميع الأدوات':'All tools'}</h2></div></div>{shown.length?<div className="grid">{shown.map(({c,i})=>{const Icon=c.icon;return <button className="card" key={c.ar} onClick={()=>setOpen(i)}><span className="icon"><Icon/></span><b>{ar?c.ar:c.en}</b><small>{ar?c.descAr:c.descEn}</small></button>})}</div>:<div className="empty">{ar?'لم نجد أداة بهذا الاسم.':'No matching tool found.'}</div>}</section><section className="dailyBanner"><div><b>{ar?'معك في كل يوم':'With you every day'}</b><span>{ar?'أدوات عملية • سريعة • في مكان واحد':'Practical • fast • all in one place'}</span></div><button onClick={()=>document.getElementById('tools')?.scrollIntoView({behavior:'smooth'})}>{ar?'اكتشف كل الأدوات':'Explore all tools'}</button></section><section className="benefits">{[[ShieldCheck,'سهولة الاستخدام','Easy to use'],[Clock3,'سريع وخفيف','Fast & light'],[ShieldCheck,'خصوصيتك أولاً','Privacy first'],[HeartPulse,'مفيد دائماً','Always useful']].map(([I,a,e]:any)=><div key={a}><I/><b>{ar?a:e}</b></div>)}</section><section className="infoMenu">{[[Info,'عن الموقع','About','about'],[Lightbulb,'كيف يفيدك؟','How it helps','help'],[Globe2,'رؤيتنا','Our vision','vision'],[CircleHelp,'الأسئلة الشائعة','FAQ','faq']].map(([I,a,e,p]:any)=><button key={p} onClick={()=>go(p)}><I/><b>{ar?a:e}</b></button>)}</section></>}
 {page!=='home'&&<section className="page"><button onClick={()=>go('home')}>{ar?'العودة للرئيسية':'Back to home'}</button><h1>{page==='about'?(ar?'عن أدواتك اليومية':'About Daily Tools'):page==='help'?(ar?'كيف يفيدك الموقع؟':'How Daily Tools Helps'):page==='vision'?(ar?'رؤيتنا':'Our Vision'):(ar?'الأسئلة الشائعة':'FAQ')}</h1><p>{page==='about'?(ar?'منصة عملية تجمع الأدوات اليومية في تجربة واضحة وسريعة تعمل من الهاتف والكمبيوتر.':'A practical platform that brings everyday utilities into one clear, fast experience on mobile and desktop.'):page==='help'?(ar?'من العمل والمال إلى المنزل والدراسة والسفر، تصل لما تحتاجه بخطوات أقل.':'From work and money to home, study and travel, get useful answers with fewer steps.'):page==='vision'?(ar?'أن تصبح أدواتك اليومية وجهتك الأولى للأدوات البسيطة التي تحتاجها كل يوم.':'To make Daily Tools your first stop for simple utilities you rely on every day.'):(ar?'الأدوات الأساسية مجانية ولا تحتاج إلى حساب. النتائج التقديرية لا تستبدل المختص أو المصدر الرسمي.':'Core tools are free and require no account. Estimates do not replace professional advice or official sources.')}</p></section>}
 <footer><b>MO</b><div><strong>{ar?'تصميم محمد العقلة':'Designed by Mohammed Al-Oqleh'}</strong><span>MOHAMMED AL-OQLEH</span></div><div><strong>{ar?'الخصوصية • الشروط • إخلاء المسؤولية':'Privacy • Terms • Disclaimer'}</strong></div></footer>
 {open!==null&&<div className="modalBack" onClick={()=>setOpen(null)}><section className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setOpen(null)}><X/></button>{(()=>{const c=data[open],Icon=c.icon,tools=ar?c.toolsAr:c.toolsEn;return <><span className="icon"><Icon/></span><h2>{ar?c.ar:c.en}</h2><div className="subgrid">{tools.map(x=><button key={x} onClick={()=>run(x)}>{x}<small>{ar?'فتح الأداة':'Open tool'}</small></button>)}</div>{['الصحة العامة','الموظف والراتب','المال والادخار'].includes(c.ar)&&<div className="notice">{ar?'النتائج تقديرية وإرشادية وليست بديلاً عن الاستشارة المتخصصة أو المصدر الرسمي.':'Results are estimates for guidance only and do not replace professional advice or official sources.'}</div>}</>})()}</section></div>}
 </main>
}