import { useMemo, useState } from 'react';
import { Calculator, CalendarDays, Clock3, Ruler, Car, PiggyBank, House, BriefcaseBusiness, FileText, GraduationCap, HeartPulse, ChefHat, QrCode, ShieldCheck, Dices, Gamepad2, Wrench, Image, Video, Link as LinkIcon, Search, X, Info, Lightbulb, Globe2, CircleHelp } from 'lucide-react';

type Lang = 'ar' | 'en';
type Category = { ar:string; en:string; descAr:string; descEn:string; toolsAr:string[]; toolsEn:string[]; icon:any };
const data: Category[] = [
['الحاسبات','Calculators','العمر، النسبة، الخصم، الوقود','Age, percentage, discount and fuel',['حاسبة العمر','النسبة المئوية','الخصم','فرق تاريخين','تقسيم الفاتورة','تكلفة الوقود'],['Age calculator','Percentage','Discount','Date difference','Split bill','Fuel cost'],Calculator],
['التاريخ والتقويم','Date & Calendar','التواريخ وعدّ الأيام','Dates and day counting',['تاريخ اليوم','فرق تاريخين','إضافة أيام','طرح أيام','رقم الأسبوع','عد تنازلي'],['Today','Date difference','Add days','Subtract days','Week number','Countdown'],CalendarDays],
['الوقت والساعة','Time & Clock','الوقت والمؤقتات','Time and timers',['ساعة رقمية','مؤقت','ساعة إيقاف','تحويل ساعات ودقائق','مدة زمنية'],['Digital clock','Timer','Stopwatch','Hours & minutes','Duration'],Clock3],
['تحويل الوحدات','Unit Conversion','الطول والوزن والمساحة','Length, weight and area',['الطول','الوزن','المساحة','الحجم','الحرارة','السرعة'],['Length','Weight','Area','Volume','Temperature','Speed'],Ruler],
['السيارة والسفر','Car & Travel','حسابات مفيدة للمسافر','Useful travel calculations',['استهلاك الوقود','تكلفة الرحلة','كم/لتر','لتر/100كم','ميل/كم','قائمة سفر'],['Fuel consumption','Trip cost','Km/L','L/100km','Miles/Km','Travel checklist'],Car],
['المال والادخار','Money & Savings','خطط وحسابات مالية بسيطة','Simple financial planning',['هدف الادخار','فائدة بسيطة','فائدة مركبة','ROI','تقسيم الميزانية','شهري/سنوي'],['Savings goal','Simple interest','Compound interest','ROI','Budget split','Monthly/Annual'],PiggyBank],
['العقار والسكن','Property & Housing','حسابات عقارية','Property calculations',['الإيجار الشهري/السنوي','سعر المتر','مساحة العقار','تقسيم الإيجار','دفعة أولى','ميزانية سكن'],['Monthly/annual rent','Price per meter','Property area','Split rent','Down payment','Housing budget'],House],
['الموظف والراتب','Employee & Salary','حسابات الموظفين والإجازات','Salary and leave calculations',['الراتب الشهري/السنوي','زيادة الراتب','العمل الإضافي','رصيد الإجازات','بدل الإجازة','نهاية الخدمة'],['Monthly/annual salary','Salary increase','Overtime','Leave balance','Leave pay','End of service'],BriefcaseBusiness],
['أدوات النصوص','Text Tools','معالجة النص داخل جهازك','Local text utilities',['عد الكلمات','عد الحروف','إزالة الفراغات','ترتيب الأسطر','إزالة التكرار','وقت القراءة'],['Word count','Character count','Trim spaces','Sort lines','Remove duplicates','Reading time'],FileText],
['التعليم','Education','حسابات وأدوات دراسية','Study utilities',['المعدل','النسبة','المتوسط','الدرجة المطلوبة','مؤقت مذاكرة','جدول الضرب'],['Average','Percentage','Mean','Required grade','Study timer','Times table'],GraduationCap],
['الصحة العامة','General Health','مؤشرات عامة غير تشخيصية','General non-diagnostic estimates',['BMI','تحويل الطول','تحويل الوزن','احتياج الماء التقريبي','BMR','Pace'],['BMI','Height conversion','Weight conversion','Water estimate','BMR','Pace'],HeartPulse],
['المطبخ','Kitchen','مقاييس ووحدات الطبخ','Cooking measurements',['جرام/كيلو','مل/لتر','كوب/مل','مئوي/فهرنهايت','مضاعفة الوصفة','مؤقت مطبخ'],['Gram/Kg','ml/L','Cup/ml','Celsius/Fahrenheit','Scale recipe','Kitchen timer'],ChefHat],
['الرموز والباركود','QR & Barcode','أدوات QR محلية','Local QR utilities',['QR لرابط','QR لنص','QR لهاتف','QR لبريد','QR لـ Wi-Fi'],['QR for link','QR for text','QR for phone','QR for email','QR for Wi-Fi'],QrCode],
['الأمان والخصوصية','Security & Privacy','أدوات حماية بسيطة','Simple privacy tools',['مولد كلمة مرور','فحص القوة محلياً','مولد PIN','عبارة مرور','نصائح حماية'],['Password generator','Password strength','PIN generator','Passphrase','Protection tips'],ShieldCheck],
['الاختيار والقرعة','Random & Draw','اختيارات عشوائية','Random choices',['رقم عشوائي','اختيار اسم','قرعة','رمي نرد','قلب عملة','عجلة اختيار'],['Random number','Pick a name','Draw','Dice','Coin flip','Choice wheel'],Dices],
['الألعاب','Games','ألعاب خفيفة','Light games',['الثعبان','XO','حجر ورقة مقص','تحدي حساب','ذاكرة','ألغاز'],['Snake','Tic Tac Toe','Rock Paper Scissors','Math challenge','Memory','Puzzles'],Gamepad2],
['أدوات يومية متنوعة','Daily Utilities','أدوات صغيرة مفيدة','Small useful utilities',['عداد نقرات','عداد أيام','مولد قائمة','تقسيم قائمة','مؤقت تركيز','ملاحظات مؤقتة'],['Click counter','Day counter','List maker','Split list','Focus timer','Temporary notes'],Wrench],
['مواقع الصور','Image Websites','روابط لخدمات خارجية موثوقة','Links to independent services',['ضغط الصور','تغيير الحجم','إزالة الخلفية','تحويل الصيغ','تصميم الصور'],['Compress images','Resize images','Remove background','Convert formats','Image design'],Image],
['مواقع الفيديو','Video Websites','روابط لخدمات خارجية موثوقة','Links to independent services',['قص الفيديو','ضغط الفيديو','تحويل الصيغة','تحرير الفيديو','تسجيل الشاشة'],['Trim video','Compress video','Convert format','Video editing','Screen recording'],Video],
['مواقع مفيدة','Useful Websites','دليل روابط منتقاة','Curated useful links',['تعليم','إنتاجية','سفر','حكومة','تقنية','مراجع'],['Education','Productivity','Travel','Government','Technology','References'],LinkIcon]
].map(x=>({ar:x[0],en:x[1],descAr:x[2],descEn:x[3],toolsAr:x[4],toolsEn:x[5],icon:x[6]})) as Category[];

export default function App(){
 const [lang,setLang]=useState<Lang>('ar'),[q,setQ]=useState(''),[open,setOpen]=useState<number|null>(null),[page,setPage]=useState<'home'|'about'|'help'|'vision'|'faq'>('home'); const ar=lang==='ar';
 const shown=useMemo(()=>data.map((c,i)=>({c,i})).filter(({c})=>(c.ar+' '+c.en+' '+c.descAr+' '+c.descEn+' '+c.toolsAr.join(' ')+' '+c.toolsEn.join(' ')).toLowerCase().includes(q.trim().toLowerCase())),[q]);
 const toggle=()=>{const n:Lang=ar?'en':'ar';setLang(n);document.documentElement.lang=n;document.documentElement.dir=n==='ar'?'rtl':'ltr';setOpen(null)};
 const go=(p:typeof page)=>{setPage(p);setOpen(null);window.scrollTo({top:0,behavior:'smooth'})};
 const run=(x:string)=>{const k=x.toLowerCase(),num=(m:string)=>Number(prompt(m)||0),out=(v:string|number)=>alert(String(v));
  if(k.includes('age')||x.includes('العمر')){const y=num(ar?'سنة الميلاد':'Birth year');if(y)out((ar?'العمر التقريبي: ':'Approximate age: ')+(new Date().getFullYear()-y))}
  else if(k.includes('percentage')||x.includes('النسبة')){const a=num(ar?'الرقم':'Value'),b=num(ar?'النسبة %':'Percentage %');out((a*b/100).toFixed(2))}
  else if(k.includes('discount')||x==='الخصم'){const a=num(ar?'السعر':'Price'),b=num(ar?'الخصم %':'Discount %');out((a*(1-b/100)).toFixed(2))}
  else if(k.includes('today')||x==='تاريخ اليوم')out(new Date().toLocaleDateString(ar?'ar-SA':'en-US',{dateStyle:'full'}));
  else if(k.includes('random number')||x==='رقم عشوائي')out(Math.floor(Math.random()*100)+1);
  else if(k.includes('dice')||x==='رمي نرد')out(Math.floor(Math.random()*6)+1);
  else if(k.includes('coin')||x==='قلب عملة')out(Math.random()<.5?(ar?'وجه':'Heads'):(ar?'كتابة':'Tails'));
  else if(k.includes('password generator')||x==='مولد كلمة مرور'){const c='ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#$%',a=new Uint32Array(16);crypto.getRandomValues(a);out(Array.from(a,n=>c[n%c.length]).join(''))}
  else if(k.includes('pin generator')||x==='مولد PIN')out(String(Math.floor(100000+Math.random()*900000)));
  else if(k==='bmi'||x==='BMI'){const w=num(ar?'الوزن بالكيلو':'Weight kg'),h=num(ar?'الطول بالسنتيمتر':'Height cm');if(w&&h)out('BMI: '+(w/(h/100)**2).toFixed(1))}
  else if(k.includes('celsius')||x.includes('مئوي')){const c=num(ar?'الدرجة المئوية':'Celsius');out((c*9/5+32).toFixed(1)+' °F')}
  else if(k.includes('miles')||x==='ميل/كم'){const m=num(ar?'المسافة بالميل':'Miles');out((m*1.609344).toFixed(2)+' km')}
  else if(k.includes('word count')||x==='عد الكلمات'||k.includes('character count')||x==='عد الحروف'){const t=prompt(ar?'أدخل النص':'Enter text')||'';out(k.includes('character')||x==='عد الحروف'?t.length:t.trim().split(/\s+/).filter(Boolean).length)}
  else if(k.includes('salary')||x.includes('الراتب')||k.includes('monthly/annual')||x==='شهري/سنوي'){const a=num(ar?'المبلغ الشهري':'Monthly amount');out((a*12).toFixed(2)+(ar?' سنوياً':' annually'))}
  else if(k.includes('fuel')||x.includes('الوقود')||x.includes('الرحلة')){const km=num(ar?'المسافة كم':'Distance km'),eff=num(ar?'الاستهلاك لتر/100كم':'Consumption L/100km'),price=num(ar?'سعر اللتر':'Price per liter');out((km*eff/100*price).toFixed(2))}
  else if(k.includes('average')||k==='mean'||x==='المعدل'||x==='المتوسط'){const a=(prompt(ar?'أدخل الأرقام مفصولة بفواصل':'Numbers separated by commas')||'').split(',').map(Number).filter(Number.isFinite);if(a.length)out((a.reduce((s,n)=>s+n,0)/a.length).toFixed(2))}
  else if(k.includes('pick')||k==='draw'||x==='اختيار اسم'||x==='قرعة'||x==='عجلة اختيار'){const a=(prompt(ar?'أدخل الخيارات مفصولة بفواصل':'Options separated by commas')||'').split(',').filter(Boolean);if(a.length)out(a[Math.floor(Math.random()*a.length)])}
  else if(k.includes('temporary notes')||x==='ملاحظات مؤقتة'){const t=prompt(ar?'اكتب ملاحظتك':'Write your note',localStorage.getItem('dailyNote')||'');if(t!==null){localStorage.setItem('dailyNote',t);out(ar?'تم الحفظ على هذا الجهاز':'Saved on this device')}}
  else out(ar?'هذه الأداة ضمن خطة التطوير المحلية للموقع.':'This utility is part of the local development plan.');
 };
 return <main dir={ar?'rtl':'ltr'}><header><button className="brand" onClick={()=>go('home')}><i>MO</i><span>{ar?'أدواتك اليومية':'Daily Tools'}<small>{ar?'كل ما تحتاجه في مكان واحد':'Everything you need in one place'}</small></span></button><nav><button onClick={()=>go('home')}>{ar?'الرئيسية':'Home'}</button><button onClick={()=>{go('home');setTimeout(()=>document.getElementById('tools')?.scrollIntoView({behavior:'smooth'}),50)}}>{ar?'كل الأدوات':'All tools'}</button><button onClick={()=>go('about')}>{ar?'عن الموقع':'About'}</button><button className="lang" onClick={toggle}>{ar?'EN':'العربية'}</button></nav></header>
 {page==='home'&&<><section className="hero"><div><span className="pill">{ar?'مجاني • سريع • بدون تسجيل':'Free • Fast • No sign-up'}</span><h1>{ar?'أدواتك اليومية':'Your Daily Tools'}</h1><p>{ar?'أدوات بسيطة .. نتائج كبيرة .. لحياة أسهل':'Simple tools. Big results. An easier day.'}</p><label className="search"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder={ar?'ابحث عن أداة...':'Search for a tool...'}/>{q&&<button onClick={()=>setQ('')}><X/></button>}</label></div><div className="heroArt"><div className="glass"><b>{ar?'أدوات عملية':'Practical tools'}</b><span>{ar?'في حياتك اليومية':'for everyday life'}</span></div></div></section><section id="tools" className="tools"><div className="sectionTitle"><div><span>{ar?'صندوق أدواتك':'Your toolbox'}</span><h2>{ar?'جميع الأدوات':'All tools'}</h2></div></div>{shown.length?<div className="grid">{shown.map(({c,i})=>{const Icon=c.icon;return <button className="card" key={c.ar} onClick={()=>setOpen(i)}><span className="icon"><Icon/></span><b>{ar?c.ar:c.en}</b><small>{ar?c.descAr:c.descEn}</small></button>})}</div>:<div className="empty">{ar?'لم نجد أداة بهذا الاسم.':'No matching tool found.'}</div>}</section><section className="dailyBanner"><div><b>{ar?'معك في كل يوم':'With you every day'}</b><span>{ar?'أدوات عملية • سريعة • في مكان واحد':'Practical • fast • all in one place'}</span></div><button onClick={()=>document.getElementById('tools')?.scrollIntoView({behavior:'smooth'})}>{ar?'اكتشف كل الأدوات':'Explore all tools'}</button></section><section className="benefits">{[[ShieldCheck,'سهولة الاستخدام','Easy to use'],[Clock3,'سريع وخفيف','Fast & light'],[ShieldCheck,'خصوصيتك أولاً','Privacy first'],[HeartPulse,'مفيد دائماً','Always useful']].map(([I,a,e]:any)=><div key={a}><I/><b>{ar?a:e}</b></div>)}</section><section className="infoMenu">{[[Info,'عن الموقع','About','about'],[Lightbulb,'كيف يفيدك؟','How it helps','help'],[Globe2,'رؤيتنا','Our vision','vision'],[CircleHelp,'الأسئلة الشائعة','FAQ','faq']].map(([I,a,e,p]:any)=><button key={p} onClick={()=>go(p)}><I/><b>{ar?a:e}</b></button>)}</section></>}
 {page!=='home'&&<section className="page"><button onClick={()=>go('home')}>{ar?'العودة للرئيسية':'Back to home'}</button><h1>{page==='about'?(ar?'عن أدواتك اليومية':'About Daily Tools'):page==='help'?(ar?'كيف يفيدك الموقع؟':'How Daily Tools Helps'):page==='vision'?(ar?'رؤيتنا':'Our Vision'):(ar?'الأسئلة الشائعة':'FAQ')}</h1><p>{page==='about'?(ar?'منصة عملية تجمع الأدوات اليومية في تجربة واضحة وسريعة تعمل من الهاتف والكمبيوتر.':'A practical platform that brings everyday utilities into one clear, fast experience on mobile and desktop.'):page==='help'?(ar?'من العمل والمال إلى المنزل والدراسة والسفر، تصل لما تحتاجه بخطوات أقل.':'From work and money to home, study and travel, get useful answers with fewer steps.'):page==='vision'?(ar?'أن تصبح أدواتك اليومية وجهتك الأولى للأدوات البسيطة التي تحتاجها كل يوم.':'To make Daily Tools your first stop for simple utilities you rely on every day.'):(ar?'الأدوات الأساسية مجانية ولا تحتاج إلى حساب. النتائج التقديرية لا تستبدل المختص أو المصدر الرسمي.':'Core tools are free and require no account. Estimates do not replace professional advice or official sources.')}</p></section>}
 <footer><b>MO</b><div><strong>{ar?'تصميم محمد العقلة':'Designed by Mohammed Al-Oqleh'}</strong><span>MOHAMMED AL-OQLEH</span></div><div><strong>{ar?'الخصوصية • الشروط • إخلاء المسؤولية':'Privacy • Terms • Disclaimer'}</strong></div></footer>
 {open!==null&&<div className="modalBack" onClick={()=>setOpen(null)}><section className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setOpen(null)}><X/></button>{(()=>{const c=data[open],Icon=c.icon,tools=ar?c.toolsAr:c.toolsEn;return <><span className="icon"><Icon/></span><h2>{ar?c.ar:c.en}</h2><div className="subgrid">{tools.map(x=><button key={x} onClick={()=>run(x)}>{x}<small>{ar?'فتح الأداة':'Open tool'}</small></button>)}</div>{['الصحة العامة','الموظف والراتب','المال والادخار'].includes(c.ar)&&<div className="notice">{ar?'النتائج تقديرية وإرشادية وليست بديلاً عن الاستشارة المتخصصة أو المصدر الرسمي.':'Results are estimates for guidance only and do not replace professional advice or official sources.'}</div>}</>})()}</section></div>}
 </main>
}
