const AR=()=>document.documentElement.dir==='rtl';
const text=(el:Element)=>Array.from(el.childNodes).filter(n=>n.nodeType===Node.TEXT_NODE).map(n=>n.textContent||'').join('').trim();
const links:Record<string,{url:string,name:string}>={
'ضغط الصور':{url:'https://www.iloveimg.com/compress-image',name:'iLoveIMG'},'Compress images':{url:'https://www.iloveimg.com/compress-image',name:'iLoveIMG'},
'تغيير الحجم':{url:'https://www.iloveimg.com/resize-image',name:'iLoveIMG'},'Resize images':{url:'https://www.iloveimg.com/resize-image',name:'iLoveIMG'},
'إزالة الخلفية':{url:'https://www.remove.bg/',name:'remove.bg'},'Remove background':{url:'https://www.remove.bg/',name:'remove.bg'},
'تحويل الصيغ':{url:'https://cloudconvert.com/',name:'CloudConvert'},'Convert formats':{url:'https://cloudconvert.com/',name:'CloudConvert'},
'تصميم الصور':{url:'https://www.canva.com/',name:'Canva'},'Image design':{url:'https://www.canva.com/',name:'Canva'},
'قص الفيديو':{url:'https://www.freeconvert.com/video-trimmer',name:'FreeConvert'},'Trim video':{url:'https://www.freeconvert.com/video-trimmer',name:'FreeConvert'},
'ضغط الفيديو':{url:'https://www.freeconvert.com/video-compressor',name:'FreeConvert'},'Compress video':{url:'https://www.freeconvert.com/video-compressor',name:'FreeConvert'},
'تحويل الصيغة':{url:'https://cloudconvert.com/video-converter',name:'CloudConvert'},'Convert format':{url:'https://cloudconvert.com/video-converter',name:'CloudConvert'},
'تحرير الفيديو':{url:'https://www.canva.com/video-editor/',name:'Canva'},'Video editing':{url:'https://www.canva.com/video-editor/',name:'Canva'},
'تسجيل الشاشة':{url:'https://www.loom.com/',name:'Loom'},'Screen recording':{url:'https://www.loom.com/',name:'Loom'},
'تعليم':{url:'https://www.khanacademy.org/',name:'Khan Academy'},'Education':{url:'https://www.khanacademy.org/',name:'Khan Academy'},
'إنتاجية':{url:'https://www.notion.com/',name:'Notion'},'Productivity':{url:'https://www.notion.com/',name:'Notion'},
'سفر':{url:'https://www.google.com/travel/',name:'Google Travel'},'Travel':{url:'https://www.google.com/travel/',name:'Google Travel'},
'تقنية':{url:'https://developer.mozilla.org/',name:'MDN Web Docs'},'Technology':{url:'https://developer.mozilla.org/',name:'MDN Web Docs'},
'مراجع':{url:'https://www.wikipedia.org/',name:'Wikipedia'},'References':{url:'https://www.wikipedia.org/',name:'Wikipedia'}
};
function guard(item:{url:string,name:string}){document.getElementById('dtExternal')?.remove();const d=document.createElement('div');d.id='dtExternal';d.dir=AR()?'rtl':'ltr';d.innerHTML=`<div class="box"><div class="badge">↗</div><h2>${AR()?'سيتم فتح موقع خارجي':'External website'}</h2><p>${AR()?`ستغادر أدواتك اليومية وتنتقل إلى ${item.name}. الموقع مستقل وله شروطه وسياسة الخصوصية الخاصة به.`:`You are leaving Daily Tools and opening ${item.name}. This is an independent service with its own terms and privacy policy.`}</p><div class="domain"></div><div class="actions"><button data-cancel>${AR()?'إلغاء':'Cancel'}</button><button class="go" data-go>${AR()?'متابعة للموقع':'Continue'}</button></div></div>`;(d.querySelector('.domain') as HTMLElement).textContent=new URL(item.url).hostname;document.body.appendChild(d);(d.querySelector('[data-cancel]') as HTMLButtonElement).onclick=()=>d.remove();(d.querySelector('[data-go]') as HTMLButtonElement).onclick=()=>{d.remove();window.open(item.url,'_blank','noopener,noreferrer')};d.onclick=e=>{if(e.target===d)d.remove()}}
const s=document.createElement('style');s.textContent=`#dtExternal{position:fixed;inset:0;z-index:2147483647;background:rgba(8,31,66,.48);backdrop-filter:blur(9px);display:grid;place-items:center;padding:18px}#dtExternal .box{width:min(94vw,470px);background:#fff;color:#0b315b;border-radius:26px;padding:25px;box-shadow:0 28px 80px rgba(7,29,73,.25)}#dtExternal .badge{width:52px;height:52px;border-radius:16px;background:#e9f6ff;color:#147dcc;display:grid;place-items:center;font-size:28px;font-weight:900}#dtExternal h2{font-size:24px;margin:17px 0 8px}#dtExternal p{color:#61758c;line-height:1.7;margin:0}#dtExternal .domain{direction:ltr;text-align:center;background:#f4f9fd;border:1px solid #dceaf5;border-radius:13px;padding:10px;margin:16px 0;color:#27648d;font-weight:800}#dtExternal .actions{display:flex;gap:9px}#dtExternal button{flex:1;border:0;border-radius:14px;padding:13px;font:inherit;font-weight:850;background:#eef5fa;color:#285779}#dtExternal .go{background:#147dcc;color:#fff}`;document.head.appendChild(s);
window.addEventListener('click',e=>{const btn=(e.target as Element|null)?.closest('.subgrid button') as HTMLElement|null;if(!btn)return;const item=links[text(btn)];if(!item)return;e.preventDefault();e.stopImmediatePropagation();guard(item)},true);export {};
