// Functional replacements for the Games category using in-page branded dialogs.
const isArabic=()=>document.documentElement.dir==='rtl';
const gameLabels=new Set(['XO','Tic Tac Toe','حجر ورقة مقص','Rock Paper Scissors','تحدي حساب','Math challenge','ألغاز','Puzzles']);
const labelOf=(button:Element)=>Array.from(button.childNodes).filter(n=>n.nodeType===Node.TEXT_NODE).map(n=>n.textContent||'').join('').trim();
const ask=(m:string,d='')=>(window as any).dtPrompt(m,d) as Promise<string|null>;
const show=(m:any)=>(window as any).dtAlert(m) as Promise<void>;
async function playTicTacToe(){const ar=isArabic();let board=Array(9).fill('·');const win=(p:string)=>[[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]].some(a=>a.every(i=>board[i]===p));for(let turn=0;turn<9;turn++){const view=`${board.slice(0,3).join('  ')}\n${board.slice(3,6).join('  ')}\n${board.slice(6,9).join('  ')}`;const raw=await ask((ar?'لعبة XO — اختر خانة من 1 إلى 9\n':'XO — choose a cell from 1 to 9\n')+view);if(raw===null)return;const i=Number(raw)-1;if(i<0||i>8||board[i]!=='·'){await show(ar?'الخانة غير متاحة، اختر رقماً من 1 إلى 9.':'That cell is unavailable. Choose 1–9.');turn--;continue}board[i]='X';if(win('X')){await show(ar?'فزت! 🎉':'You won! 🎉');return}const empty=board.map((v,i)=>v==='·'?i:-1).filter(i=>i>=0);if(!empty.length)break;board[empty[Math.floor(Math.random()*empty.length)]]='O';if(win('O')){await show(ar?'فاز الكمبيوتر. جرّب مرة ثانية.':'Computer won. Try again.');return}}await show(ar?'تعادل!':'Draw!')}
async function rps(){const ar=isArabic(),choices=ar?['حجر','ورقة','مقص']:['rock','paper','scissors'];const raw=await ask(ar?'اكتب: حجر أو ورقة أو مقص':'Type: rock, paper, or scissors');if(raw===null)return;const input=raw.trim().toLowerCase(),map:Record<string,number>={حجر:0,ورقة:1,مقص:2,rock:0,paper:1,scissors:2};if(!(input in map)){await show(ar?'اختيار غير صحيح.':'Invalid choice.');return}const u=map[input],c=Math.floor(Math.random()*3),result=u===c?0:(u-c+3)%3===1?1:-1;await show(`${ar?'اختيار الكمبيوتر':'Computer'}: ${choices[c]}\n${result===0?(ar?'تعادل':'Draw'):result===1?(ar?'فزت! 🎉':'You won! 🎉'):(ar?'فاز الكمبيوتر':'Computer won')}`)}
async function mathChallenge(){const ar=isArabic(),a=Math.ceil(Math.random()*30),b=Math.ceil(Math.random()*30),op=Math.random()<.5?'+':'×',answer=op==='+'?a+b:a*b;const v=await ask(`${a} ${op} ${b} = ?`);if(v===null)return;await show(Number(v)===answer?(ar?'إجابة صحيحة! 🎉':'Correct! 🎉'):(ar?`الإجابة الصحيحة: ${answer}`:`Correct answer: ${answer}`))}
async function puzzle(){const ar=isArabic(),p=ar?[[`ما الشيء الذي كلما أخذت منه كبر؟`,'الحفرة'],['له أسنان ولا يعض، ما هو؟','المشط'],['يمشي بلا أرجل ويبكي بلا عيون، ما هو؟','السحاب']]:[['What gets bigger the more you take away?','A hole'],['What has teeth but cannot bite?','A comb'],['What can travel around the world while staying in a corner?','A stamp']];const[q,a]=p[Math.floor(Math.random()*p.length)];const v=await ask(q);if(v===null)return;await show(`${ar?'الإجابة':'Answer'}: ${a}`)}
window.addEventListener('click',e=>{const target=e.target as Element|null,button=target?.closest('.subgrid button');if(!button)return;const label=labelOf(button);if(!gameLabels.has(label))return;e.preventDefault();e.stopImmediatePropagation();if(label==='XO'||label==='Tic Tac Toe')void playTicTacToe();else if(label==='حجر ورقة مقص'||label==='Rock Paper Scissors')void rps();else if(label==='تحدي حساب'||label==='Math challenge')void mathChallenge();else void puzzle()},true);
