const AR=()=>document.documentElement.dir==='rtl';
const css=`#dtDialog{position:fixed;inset:0;z-index:2147483647;background:rgba(7,29,73,.42);display:grid;place-items:center;padding:22px;backdrop-filter:blur(8px)}#dtDialog .dtbox{box-sizing:border-box;width:min(92vw,430px);max-height:86vh;overflow:auto;background:#fff;border:1px solid #d9e8f5;border-radius:26px;padding:24px;box-shadow:0 28px 80px rgba(7,29,73,.24);font-family:inherit;color:#0b315b}#dtDialog .dtbrand{font-size:17px;font-weight:900;color:#1976c9;margin-bottom:14px}#dtDialog .dtmsg{font-size:20px;line-height:1.7;font-weight:700;margin:0 0 18px;white-space:pre-wrap;overflow-wrap:anywhere}#dtDialog input{box-sizing:border-box;width:100%;border:1px solid #cbddeb;background:#f8fbfe;color:#0b315b;border-radius:14px;padding:14px 16px;font:inherit;font-size:17px;outline:none}#dtDialog input:focus{border-color:#2589d8;box-shadow:0 0 0 3px #2589d820}#dtDialog .dtbuttons{display:flex;gap:10px;margin-top:18px}#dtDialog button{flex:1;border:0;border-radius:14px;padding:12px 14px;font:inherit;font-size:16px;font-weight:800;cursor:pointer}#dtDialog .ok{background:#1478c9;color:#fff}#dtDialog .cancel{background:#eef6fc;color:#285779}@media(max-width:650px){#dtDialog{padding:16px}#dtDialog .dtbox{width:min(94vw,430px);padding:22px;border-radius:24px}#dtDialog .dtmsg{font-size:19px}#dtDialog input{font-size:18px;min-height:54px}}`;
function mount(){if(!document.getElementById('dtDialogStyle')){const s=document.createElement('style');s.id='dtDialogStyle';s.textContent=css;document.head.appendChild(s)}}
function box(message:string,input:boolean,def=''){mount();document.getElementById('dtDialog')?.remove();const d=document.createElement('div');d.id='dtDialog';d.dir=AR()?'rtl':'ltr';d.innerHTML=`<div class="dtbox"><div class="dtbrand">${AR()?'أدواتك اليومية':'Daily Tools'}</div><div class="dtmsg"></div>${input?'<input class="dtinput" autocomplete="off">':''}<div class="dtbuttons">${input?`<button class="cancel">${AR()?'إلغاء':'Cancel'}</button>`:''}<button class="ok">${AR()?'موافق':'OK'}</button></div></div>`;(d.querySelector('.dtmsg') as HTMLElement).textContent=message;if(input)(d.querySelector('.dtinput') as HTMLInputElement).value=def;document.body.appendChild(d);return d}
(window as any).dtPrompt=(message:string,def='')=>new Promise<string|null>(resolve=>{const d=box(message,true,def),i=d.querySelector('.dtinput') as HTMLInputElement,done=(v:string|null)=>{d.remove();resolve(v)};(d.querySelector('.ok') as HTMLButtonElement).onclick=()=>done(i.value);(d.querySelector('.cancel') as HTMLButtonElement).onclick=()=>done(null);d.onclick=e=>{if(e.target===d)done(null)};i.onkeydown=e=>{if(e.key==='Enter')done(i.value);if(e.key==='Escape')done(null)};setTimeout(()=>i.focus(),20)});
(window as any).dtAlert=(message:any)=>new Promise<void>(resolve=>{const d=box(String(message),false),done=()=>{d.remove();resolve()};(d.querySelector('.ok') as HTMLButtonElement).onclick=done;d.onclick=e=>{if(e.target===d)done()}});
// Never allow browser-native prompt/alert UI to expose the GitHub Pages hostname.
window.prompt=((message?:string,defaultValue?:string)=>{void (window as any).dtPrompt(message||'',defaultValue||'');return null}) as typeof window.prompt;
window.alert=((message?:any)=>{void (window as any).dtAlert(message)}) as typeof window.alert;
window.addEventListener('click',async e=>{const target=e.target as Element|null,btn=target?.closest('.subgrid button') as HTMLElement|null;if(!btn)return;if(btn.dataset.dtMigrated==='1')return;const label=Array.from(btn.childNodes).filter(n=>n.nodeType===Node.TEXT_NODE).map(n=>n.textContent||'').join('').trim();if(!label)return;const legacy=(window as any).__dailyToolsRun;if(typeof legacy!=='function')return;e.preventDefault();e.stopImmediatePropagation();await legacy(label)},true);
export {};
