import {createRoot,Root} from 'react-dom/client';
import CalculatorTools from './CalculatorTools';
type Tool='age'|'percentage'|'discount'|'dates'|'bill';
const map:Record<string,Tool>={'حاسبة العمر':'age','Age calculator':'age','النسبة المئوية':'percentage','Percentage':'percentage','الخصم':'discount','Discount':'discount','فرق تاريخين':'dates','Date difference':'dates','تقسيم الفاتورة':'bill','Split bill':'bill'};
let root:Root|null=null;
const text=(el:Element)=>Array.from(el.childNodes).filter(n=>n.nodeType===Node.TEXT_NODE).map(n=>n.textContent||'').join('').trim();
const en:Record<string,string>={'أدواتك اليومية':'Daily Tools','حاسبة العمر':'Age calculator','تاريخ الميلاد':'Birth date','احسب حتى تاريخ':'Calculate until','اختياري — الافتراضي اليوم':'Optional — defaults to today','أدخل تاريخ الميلاد لعرض النتيجة.':'Enter your birth date to see the result.','مسح':'Clear','حاسبة النسبة المئوية':'Percentage calculator','X% من Y':'X% of Y','X كم % من Y':'X is what % of Y','زيادة / نقصان':'Increase / decrease','النسبة %':'Percentage %','الجزء':'Part','القيمة القديمة':'Old value','الرقم':'Number','الكل':'Total','القيمة الجديدة':'New value','نسخ النتيجة':'Copy result','حاسبة الخصم':'Discount calculator','السعر الأصلي':'Original price','نسبة الخصم %':'Discount %','العملة':'Currency','+ إضافة ضريبة':'+ Add tax','الضريبة %':'Tax %','فارق التاريخ':'Date difference','من تاريخ':'From date','إلى تاريخ':'To date','اليوم':'Today','أمس':'Yesterday','منذ أسبوع':'A week ago','⇄ تبديل':'⇄ Swap','أيام العمل فقط (الأحد–الخميس)':'Business days only (Sun–Thu)','تقسيم الفاتورة':'Split bill','إجمالي الفاتورة':'Bill total','عدد الأشخاص':'Number of people','البقشيش %':'Tip %','اختياري':'Optional','نسخ للمشاركة':'Copy to share','البقشيش:':'Tip:','الإجمالي:':'Total:','لكل شخص:':'Per person:','مبلغ الخصم:':'Discount amount:','بعد الخصم:':'After discount:','الضريبة:':'Tax:','إجمالي الأيام:':'Total days:','الأسابيع:':'Weeks:','أيام العمل:':'Business days:','الأشهر':'Months','الأسابيع':'Weeks','الأيام':'Days','يوم الميلاد:':'Birth weekday:','البرج:':'Zodiac:','حتى عيد الميلاد القادم:':'Until next birthday:'};
function translate(){if(document.documentElement.lang!=='en')return;const host=document.getElementById('calculator-tool-root');if(!host)return;host.setAttribute('dir','ltr');host.querySelectorAll('*').forEach(el=>{el.childNodes.forEach(n=>{if(n.nodeType!==Node.TEXT_NODE)return;const raw=n.textContent||'',s=raw.trim();if(!s)return;const exact=en[s];if(exact){n.textContent=raw.replace(s,exact);return}let v=s;for(const [a,b] of Object.entries(en))v=v.split(a).join(b);v=v.replace(/(\d+) سنة، (\d+) شهر، (\d+) يوم/g,'$1 years, $2 months, $3 days').replace(/(\d+) يوم/g,'$1 days').replace(' سنة، ',' years, ').replace(' شهر، ',' months, ').replace(' يوم',' days').replace('زيادة','increase').replace('نقصان','decrease');if(v!==s)n.textContent=raw.replace(s,v)})});const close=host.querySelector('.calcClose');if(close)close.setAttribute('aria-label','Close')}
window.addEventListener('click',e=>{const target=e.target as Element|null,button=target?.closest('.subgrid button');if(!button)return;const tool=map[text(button)];if(!tool)return;e.preventDefault();e.stopImmediatePropagation();let host=document.getElementById('calculator-tool-root');if(!host){host=document.createElement('div');host.id='calculator-tool-root';document.body.appendChild(host);root=createRoot(host)}root!.render(<CalculatorTools tool={tool} onClose={()=>root!.render(<></>)}/>);requestAnimationFrame(()=>{translate();const h=document.getElementById('calculator-tool-root');if(h)new MutationObserver(()=>translate()).observe(h,{childList:true,subtree:true,characterData:true})})},true);
